public class CoffeeShopRunner 
{
    public static void main(String args[]) 
	{
        new CoffeeShopRunner();

        CoffeeShop myCoffee = new CoffeeShop();
        myCoffee.blend = "House Blend";
        myCoffee.origin = "Brazil";
        myCoffee.roaster = "Java Joe's Roastery";
        myCoffee.roastLevel = "Medium";
        myCoffee.grindType = "Whole Bean";
        myCoffee.price = 12.99;
        myCoffee.quantityInStock = 100;
        myCoffee.isOrganic = true;
        myCoffee.isFairTrade = true;
        myCoffee.isDecaf = false;
		myCoffee.name = "Black Coffee";
		myCoffee.quantity = 30.2f;
		myCoffee.varieties = 18; 
        System.out.println("Blend: " + myCoffee.blend);
        System.out.println("Origin: " + myCoffee.origin);
        System.out.println("Roaster: " + myCoffee.roaster);
        System.out.println("Roast Level: " + myCoffee.roastLevel);
        System.out.println("Grind Type: " + myCoffee.grindType);
        System.out.println("Price: $" + myCoffee.price);
        System.out.println("Quantity in Stock: " + myCoffee.quantityInStock);
        System.out.println("Organic: " + myCoffee.isOrganic);
        System.out.println("Fair Trade: " + myCoffee.isFairTrade);
        System.out.println("Decaf: " + myCoffee.isDecaf);
		System.out.println("Name:" + myCoffee.name);
		System.out.println("Quantity:" + myCoffee.quantity);
		System.out.println("Varieties:" + myCoffee.varieties);
		
		CoffeeShop myCoffee2 = new CoffeeShop();
        myCoffee2.blend = "House Blend";
        myCoffee2.origin = "Brazil";
        myCoffee2.roaster = "Java Joe's Roastery";
        myCoffee2.roastLevel = "Medium";
        myCoffee2.grindType = "Whole Bean";
        myCoffee2.price = 12.99;
        myCoffee2.quantityInStock = 100;
        myCoffee2.isOrganic = true;
        myCoffee2.isFairTrade = true;
        myCoffee2.isDecaf = false;
		myCoffee2.name = "Black Coffee";
		myCoffee2.quantity = 30.2f;
		myCoffee2.varieties = 18; 
        System.out.println("Blend: " + myCoffee2.blend);
        System.out.println("Origin: " + myCoffee2.origin);
        System.out.println("Roaster: " + myCoffee2.roaster);
        System.out.println("Roast Level: " + myCoffee2.roastLevel);
        System.out.println("Grind Type: " + myCoffee2.grindType);
        System.out.println("Price: $" + myCoffee2.price);
        System.out.println("Quantity in Stock: " + myCoffee2.quantityInStock);
        System.out.println("Organic: " + myCoffee2.isOrganic);
        System.out.println("Fair Trade: " + myCoffee2.isFairTrade);
        System.out.println("Decaf: " + myCoffee2.isDecaf);
		System.out.println("Name:" + myCoffee2.name);
		System.out.println("Quantity:" + myCoffee2.quantity);
		System.out.println("Varieties:" + myCoffee2.varieties);
		
		CoffeeShop myCoffee3 = new CoffeeShop();
        myCoffee3.blend = "House Blend";
        myCoffee3.origin = "Brazil";
        myCoffee3.roaster = "Java Joe's Roastery";
        myCoffee3.roastLevel = "Medium";
        myCoffee3.grindType = "Whole Bean";
        myCoffee3.price = 12.99;
        myCoffee3.quantityInStock = 100;
        myCoffee3.isOrganic = true;
        myCoffee3.isFairTrade = true;
        myCoffee3.isDecaf = false;
		myCoffee3.name = "Black Coffee";
		myCoffee3.quantity = 30.2f;
		myCoffee3.varieties = 18; 
        System.out.println("Blend: " + myCoffee3.blend);
        System.out.println("Origin: " + myCoffee3.origin);
        System.out.println("Roaster: " + myCoffee3.roaster);
        System.out.println("Roast Level: " + myCoffee3.roastLevel);
        System.out.println("Grind Type: " + myCoffee3.grindType);
        System.out.println("Price: $" + myCoffee3.price);
        System.out.println("Quantity in Stock: " + myCoffee3.quantityInStock);
        System.out.println("Organic: " + myCoffee3.isOrganic);
        System.out.println("Fair Trade: " + myCoffee3.isFairTrade);
        System.out.println("Decaf: " + myCoffee3.isDecaf);
		System.out.println("Name:" + myCoffee3.name);
		System.out.println("Quantity:" + myCoffee3.quantity);
		System.out.println("Varieties:" + myCoffee3.varieties);
		
		CoffeeShop myCoffee4 = new CoffeeShop();
        myCoffee4.blend = "House Blend";
        myCoffee4.origin = "Brazil";
        myCoffee4.roaster = "Java Joe's Roastery";
        myCoffee4.roastLevel = "Medium";
        myCoffee4.grindType = "Whole Bean";
        myCoffee4.price = 12.99;
        myCoffee4.quantityInStock = 100;
        myCoffee4.isOrganic = true;
        myCoffee4.isFairTrade = true;
        myCoffee4.isDecaf = false;
		myCoffee4.name = "Black Coffee";
		myCoffee4.quantity = 30.2f;
		myCoffee4.varieties = 18; 
        System.out.println("Blend: " + myCoffee4.blend);
        System.out.println("Origin: " + myCoffee4.origin);
        System.out.println("Roaster: " + myCoffee4.roaster);
        System.out.println("Roast Level: " + myCoffee4.roastLevel);
        System.out.println("Grind Type: " + myCoffee4.grindType);
        System.out.println("Price: $" + myCoffee4.price);
        System.out.println("Quantity in Stock: " + myCoffee4.quantityInStock);
        System.out.println("Organic: " + myCoffee4.isOrganic);
        System.out.println("Fair Trade: " + myCoffee4.isFairTrade);
        System.out.println("Decaf: " + myCoffee4.isDecaf);
		System.out.println("Name:" + myCoffee4.name);
		System.out.println("Quantity:" + myCoffee4.quantity);
		System.out.println("Varieties:" + myCoffee4.varieties);
		
		CoffeeShop myCoffee5 = new CoffeeShop();
        myCoffee5.blend = "House Blend";
        myCoffee5.origin = "Brazil";
        myCoffee5.roaster = "Java Joe's Roastery";
        myCoffee5.roastLevel = "Medium";
        myCoffee5.grindType = "Whole Bean";
        myCoffee5.price = 12.99;
        myCoffee5.quantityInStock = 100;
        myCoffee5.isOrganic = true;
        myCoffee5.isFairTrade = true;
        myCoffee5.isDecaf = false;
		myCoffee5.name = "Black Coffee";
		myCoffee5.quantity = 30.2f;
		myCoffee5.varieties = 18; 
        System.out.println("Blend: " + myCoffee5.blend);
        System.out.println("Origin: " + myCoffee5.origin);
        System.out.println("Roaster: " + myCoffee5.roaster);
        System.out.println("Roast Level: " + myCoffee5.roastLevel);
        System.out.println("Grind Type: " + myCoffee5.grindType);
        System.out.println("Price: $" + myCoffee5.price);
        System.out.println("Quantity in Stock: " + myCoffee5.quantityInStock);
        System.out.println("Organic: " + myCoffee5.isOrganic);
        System.out.println("Fair Trade: " + myCoffee5.isFairTrade);
        System.out.println("Decaf: " + myCoffee5.isDecaf);
		System.out.println("Name:" + myCoffee5.name);
		System.out.println("Quantity:" + myCoffee5.quantity);
		System.out.println("Varieties:" + myCoffee5.varieties);
		
		CoffeeShop myCoffee6 = new CoffeeShop();
        myCoffee6.blend = "House Blend";
        myCoffee6.origin = "Brazil";
        myCoffee6.roaster = "Java Joe's Roastery";
        myCoffee6.roastLevel = "Medium";
        myCoffee6.grindType = "Whole Bean";
        myCoffee6.price = 12.99;
        myCoffee6.quantityInStock = 100;
        myCoffee6.isOrganic = true;
        myCoffee6.isFairTrade = true;
        myCoffee6.isDecaf = false;
		myCoffee6.name = "Black Coffee";
		myCoffee6.quantity = 30.2f;
		myCoffee6.varieties = 18; 
        System.out.println("Blend: " + myCoffee6.blend);
        System.out.println("Origin: " + myCoffee6.origin);
        System.out.println("Roaster: " + myCoffee6.roaster);
        System.out.println("Roast Level: " + myCoffee6.roastLevel);
        System.out.println("Grind Type: " + myCoffee6.grindType);
        System.out.println("Price: $" + myCoffee6.price);
        System.out.println("Quantity in Stock: " + myCoffee6.quantityInStock);
        System.out.println("Organic: " + myCoffee6.isOrganic);
        System.out.println("Fair Trade: " + myCoffee6.isFairTrade);
        System.out.println("Decaf: " + myCoffee6.isDecaf);
		System.out.println("Name:" + myCoffee6.name);
		System.out.println("Quantity:" + myCoffee6.quantity);
		System.out.println("Varieties:" + myCoffee6.varieties);
		
		CoffeeShop myCoffee7 = new CoffeeShop();
        myCoffee7.blend = "House Blend";
        myCoffee7.origin = "Brazil";
        myCoffee7.roaster = "Java Joe's Roastery";
        myCoffee7.roastLevel = "Medium";
        myCoffee7.grindType = "Whole Bean";
        myCoffee7.price = 12.99;
        myCoffee7.quantityInStock = 100;
        myCoffee7.isOrganic = true;
        myCoffee7.isFairTrade = true;
        myCoffee7.isDecaf = false;
		myCoffee7.name = "Black Coffee";
		myCoffee7.quantity = 30.2f;
		myCoffee7.varieties = 18; 
        System.out.println("Blend: " + myCoffee7.blend);
        System.out.println("Origin: " + myCoffee7.origin);
        System.out.println("Roaster: " + myCoffee7.roaster);
        System.out.println("Roast Level: " + myCoffee7.roastLevel);
        System.out.println("Grind Type: " + myCoffee7.grindType);
        System.out.println("Price: $" + myCoffee7.price);
        System.out.println("Quantity in Stock: " + myCoffee7.quantityInStock);
        System.out.println("Organic: " + myCoffee7.isOrganic);
        System.out.println("Fair Trade: " + myCoffee7.isFairTrade);
        System.out.println("Decaf: " + myCoffee7.isDecaf);
		System.out.println("Name:" + myCoffee7.name);
		System.out.println("Quantity:" + myCoffee7.quantity);
		System.out.println("Varieties:" + myCoffee7.varieties);
		
		CoffeeShop myCoffee8 = new CoffeeShop();
        myCoffee8.blend = "House Blend";
        myCoffee8.origin = "Brazil";
        myCoffee8.roaster = "Java Joe's Roastery";
        myCoffee8.roastLevel = "Medium";
        myCoffee8.grindType = "Whole Bean";
        myCoffee8.price = 12.99;
        myCoffee8.quantityInStock = 100;
        myCoffee8.isOrganic = true;
        myCoffee8.isFairTrade = true;
        myCoffee8.isDecaf = false;
		myCoffee8.name = "Black Coffee";
		myCoffee8.quantity = 30.2f;
		myCoffee8.varieties = 18; 
        System.out.println("Blend: " + myCoffee8.blend);
        System.out.println("Origin: " + myCoffee8.origin);
        System.out.println("Roaster: " + myCoffee8.roaster);
        System.out.println("Roast Level: " + myCoffee8.roastLevel);
        System.out.println("Grind Type: " + myCoffee8.grindType);
        System.out.println("Price: $" + myCoffee8.price);
        System.out.println("Quantity in Stock: " + myCoffee8.quantityInStock);
        System.out.println("Organic: " + myCoffee8.isOrganic);
        System.out.println("Fair Trade: " + myCoffee8.isFairTrade);
        System.out.println("Decaf: " + myCoffee8.isDecaf);
		System.out.println("Name:" + myCoffee8.name);
		System.out.println("Quantity:" + myCoffee8.quantity);
		System.out.println("Varieties:" + myCoffee8.varieties);
		
		CoffeeShop myCoffee9 = new CoffeeShop();
        myCoffee9.blend = "House Blend";
        myCoffee9.origin = "Brazil";
        myCoffee9.roaster = "Java Joe's Roastery";
        myCoffee9.roastLevel = "Medium";
        myCoffee9.grindType = "Whole Bean";
        myCoffee9.price = 12.99;
        myCoffee9.quantityInStock = 100;
        myCoffee9.isOrganic = true;
        myCoffee9.isFairTrade = true;
        myCoffee9.isDecaf = false;
		myCoffee9.name = "Black Coffee";
		myCoffee9.quantity = 30.2f;
		myCoffee9.varieties = 18; 
        System.out.println("Blend: " + myCoffee9.blend);
        System.out.println("Origin: " + myCoffee9.origin);
        System.out.println("Roaster: " + myCoffee9.roaster);
        System.out.println("Roast Level: " + myCoffee9.roastLevel);
        System.out.println("Grind Type: " + myCoffee9.grindType);
        System.out.println("Price: $" + myCoffee9.price);
        System.out.println("Quantity in Stock: " + myCoffee9.quantityInStock);
        System.out.println("Organic: " + myCoffee9.isOrganic);
        System.out.println("Fair Trade: " + myCoffee9.isFairTrade);
        System.out.println("Decaf: " + myCoffee9.isDecaf);
		System.out.println("Name:" + myCoffee9.name);
		System.out.println("Quantity:" + myCoffee9.quantity);
		System.out.println("Varieties:" + myCoffee9.varieties);
		
		CoffeeShop myCoffee10 = new CoffeeShop();
        myCoffee10.blend = "House Blend";
        myCoffee10.origin = "Brazil";
        myCoffee10.roaster = "Java Joe's Roastery";
        myCoffee10.roastLevel = "Medium";
        myCoffee10.grindType = "Whole Bean";
        myCoffee10.price = 12.99;
        myCoffee10.quantityInStock = 100;
        myCoffee10.isOrganic = true;
        myCoffee10.isFairTrade = true;
        myCoffee10.isDecaf = false;
		myCoffee10.name = "Black Coffee";
		myCoffee10.quantity = 30.2f;
		myCoffee10.varieties = 18; 
        System.out.println("Blend: " + myCoffee10.blend);
        System.out.println("Origin: " + myCoffee10.origin);
        System.out.println("Roaster: " + myCoffee10.roaster);
        System.out.println("Roast Level: " + myCoffee10.roastLevel);
        System.out.println("Grind Type: " + myCoffee10.grindType);
        System.out.println("Price: $" + myCoffee10.price);
        System.out.println("Quantity in Stock: " + myCoffee10.quantityInStock);
        System.out.println("Organic: " + myCoffee10.isOrganic);
        System.out.println("Fair Trade: " + myCoffee10.isFairTrade);
        System.out.println("Decaf: " + myCoffee10.isDecaf);
		System.out.println("Name:" + myCoffee10.name);
		System.out.println("Quantity:" + myCoffee10.quantity);
		System.out.println("Varieties:" + myCoffee10.varieties);
    }
}
