public class ConcertRunner 
{
    public static void main(String args[])
	{
        new ConcertRunner();

        Concert liveConcert = new Concert();
        liveConcert.concertID = "CON7890";
        liveConcert.artist = "Taylor Swift";
        liveConcert.genre = "Pop";
        liveConcert.venue = "Wembley Stadium";
        liveConcert.city = "London";
        liveConcert.country = "UK";
        liveConcert.date = "2024-09-15";
        liveConcert.time = "19:00";
        liveConcert.durationMinutes = 120;
        liveConcert.ticketPrice = 150.00;
        liveConcert.totalTickets = 80000;
        liveConcert.availableTickets = 5000;
        liveConcert.isOutdoor = true;
        liveConcert.organizer = "Music Events Ltd.";
        liveConcert.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert.artist);
        System.out.println("The liveConcert genre is: " + liveConcert.genre);
        System.out.println("The liveConcert venue is: " + liveConcert.venue);
        System.out.println("The liveConcert city is: " + liveConcert.city);
        System.out.println("The liveConcert country is: " + liveConcert.country);
        System.out.println("The liveConcert date is: " + liveConcert.date);
        System.out.println("The liveConcert time is: " + liveConcert.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert.contactNumber);
		
		Concert liveConcert2 = new Concert();
        liveConcert2.concertID = "CON7890";
        liveConcert2.artist = "Taylor Swift";
        liveConcert2.genre = "Pop";
        liveConcert2.venue = "Wembley Stadium";
        liveConcert2.city = "London";
        liveConcert2.country = "UK";
        liveConcert2.date = "2024-09-15";
        liveConcert2.time = "19:00";
        liveConcert2.durationMinutes = 120;
        liveConcert2.ticketPrice = 150.00;
        liveConcert2.totalTickets = 80000;
        liveConcert2.availableTickets = 5000;
        liveConcert2.isOutdoor = true;
        liveConcert2.organizer = "Music Events Ltd.";
        liveConcert2.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert2.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert2.artist);
        System.out.println("The liveConcert genre is: " + liveConcert2.genre);
        System.out.println("The liveConcert venue is: " + liveConcert2.venue);
        System.out.println("The liveConcert city is: " + liveConcert2.city);
        System.out.println("The liveConcert country is: " + liveConcert2.country);
        System.out.println("The liveConcert date is: " + liveConcert2.date);
        System.out.println("The liveConcert time is: " + liveConcert2.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert2.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert2.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert2.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert2.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert2.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert2.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert2.contactNumber);
		
		Concert liveConcert3 = new Concert();
        liveConcert3.concertID = "CON7890";
        liveConcert3.artist = "Taylor Swift";
        liveConcert3.genre = "Pop";
        liveConcert3.venue = "Wembley Stadium";
        liveConcert3.city = "London";
        liveConcert3.country = "UK";
        liveConcert3.date = "2024-09-15";
        liveConcert3.time = "19:00";
        liveConcert3.durationMinutes = 120;
        liveConcert3.ticketPrice = 150.00;
        liveConcert3.totalTickets = 80000;
        liveConcert3.availableTickets = 5000;
        liveConcert3.isOutdoor = true;
        liveConcert3.organizer = "Music Events Ltd.";
        liveConcert3.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert3.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert3.artist);
        System.out.println("The liveConcert genre is: " + liveConcert3.genre);
        System.out.println("The liveConcert venue is: " + liveConcert3.venue);
        System.out.println("The liveConcert city is: " + liveConcert3.city);
        System.out.println("The liveConcert country is: " + liveConcert3.country);
        System.out.println("The liveConcert date is: " + liveConcert3.date);
        System.out.println("The liveConcert time is: " + liveConcert3.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert3.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert3.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert3.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert3.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert3.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert3.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert3.contactNumber);
		
		Concert liveConcert4 = new Concert();
        liveConcert4.concertID = "CON7890";
        liveConcert4.artist = "Taylor Swift";
        liveConcert4.genre = "Pop";
        liveConcert4.venue = "Wembley Stadium";
        liveConcert4.city = "London";
        liveConcert4.country = "UK";
        liveConcert4.date = "2024-09-15";
        liveConcert4.time = "19:00";
        liveConcert4.durationMinutes = 120;
        liveConcert4.ticketPrice = 150.00;
        liveConcert4.totalTickets = 80000;
        liveConcert4.availableTickets = 5000;
        liveConcert4.isOutdoor = true;
        liveConcert4.organizer = "Music Events Ltd.";
        liveConcert4.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert4.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert4.artist);
        System.out.println("The liveConcert genre is: " + liveConcert4.genre);
        System.out.println("The liveConcert venue is: " + liveConcert4.venue);
        System.out.println("The liveConcert city is: " + liveConcert4.city);
        System.out.println("The liveConcert country is: " + liveConcert4.country);
        System.out.println("The liveConcert date is: " + liveConcert4.date);
        System.out.println("The liveConcert time is: " + liveConcert4.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert4.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert4.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert4.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert4.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert4.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert4.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert4.contactNumber);
		
		Concert liveConcert5 = new Concert();
        liveConcert5.concertID = "CON7890";
        liveConcert5.artist = "Taylor Swift";
        liveConcert5.genre = "Pop";
        liveConcert5.venue = "Wembley Stadium";
        liveConcert5.city = "London";
        liveConcert5.country = "UK";
        liveConcert5.date = "2024-09-15";
        liveConcert5.time = "19:00";
        liveConcert5.durationMinutes = 120;
        liveConcert5.ticketPrice = 150.00;
        liveConcert5.totalTickets = 80000;
        liveConcert5.availableTickets = 5000;
        liveConcert5.isOutdoor = true;
        liveConcert5.organizer = "Music Events Ltd.";
        liveConcert5.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert5.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert5.artist);
        System.out.println("The liveConcert genre is: " + liveConcert5.genre);
        System.out.println("The liveConcert venue is: " + liveConcert5.venue);
        System.out.println("The liveConcert city is: " + liveConcert5.city);
        System.out.println("The liveConcert country is: " + liveConcert5.country);
        System.out.println("The liveConcert date is: " + liveConcert5.date);
        System.out.println("The liveConcert time is: " + liveConcert5.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert5.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert5.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert5.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert5.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert5.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert5.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert5.contactNumber);
		
		Concert liveConcert6 = new Concert();
        liveConcert6.concertID = "CON7890";
        liveConcert6.artist = "Taylor Swift";
        liveConcert6.genre = "Pop";
        liveConcert6.venue = "Wembley Stadium";
        liveConcert6.city = "London";
        liveConcert6.country = "UK";
        liveConcert6.date = "2024-09-15";
        liveConcert6.time = "19:00";
        liveConcert6.durationMinutes = 120;
        liveConcert6.ticketPrice = 150.00;
        liveConcert6.totalTickets = 80000;
        liveConcert6.availableTickets = 5000;
        liveConcert6.isOutdoor = true;
        liveConcert6.organizer = "Music Events Ltd.";
        liveConcert6.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert6.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert6.artist);
        System.out.println("The liveConcert genre is: " + liveConcert6.genre);
        System.out.println("The liveConcert venue is: " + liveConcert6.venue);
        System.out.println("The liveConcert city is: " + liveConcert6.city);
        System.out.println("The liveConcert country is: " + liveConcert6.country);
        System.out.println("The liveConcert date is: " + liveConcert6.date);
        System.out.println("The liveConcert time is: " + liveConcert6.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert6.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert6.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert6.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert6.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert6.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert6.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert6.contactNumber);
		
		Concert liveConcert7 = new Concert();
        liveConcert7.concertID = "CON7890";
        liveConcert7.artist = "Taylor Swift";
        liveConcert7.genre = "Pop";
        liveConcert7.venue = "Wembley Stadium";
        liveConcert7.city = "London";
        liveConcert7.country = "UK";
        liveConcert7.date = "2024-09-15";
        liveConcert7.time = "19:00";
        liveConcert7.durationMinutes = 120;
        liveConcert7.ticketPrice = 150.00;
        liveConcert7.totalTickets = 80000;
        liveConcert7.availableTickets = 5000;
        liveConcert7.isOutdoor = true;
        liveConcert7.organizer = "Music Events Ltd.";
        liveConcert7.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert7.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert7.artist);
        System.out.println("The liveConcert genre is: " + liveConcert7.genre);
        System.out.println("The liveConcert venue is: " + liveConcert7.venue);
        System.out.println("The liveConcert city is: " + liveConcert7.city);
        System.out.println("The liveConcert country is: " + liveConcert7.country);
        System.out.println("The liveConcert date is: " + liveConcert7.date);
        System.out.println("The liveConcert time is: " + liveConcert7.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert7.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert7.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert7.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert7.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert7.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert7.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert7.contactNumber);
		
		Concert liveConcert8 = new Concert();
        liveConcert8.concertID = "CON7890";
        liveConcert8.artist = "Taylor Swift";
        liveConcert8.genre = "Pop";
        liveConcert8.venue = "Wembley Stadium";
        liveConcert8.city = "London";
        liveConcert8.country = "UK";
        liveConcert8.date = "2024-09-15";
        liveConcert8.time = "19:00";
        liveConcert8.durationMinutes = 120;
        liveConcert8.ticketPrice = 150.00;
        liveConcert8.totalTickets = 80000;
        liveConcert8.availableTickets = 5000;
        liveConcert8.isOutdoor = true;
        liveConcert8.organizer = "Music Events Ltd.";
        liveConcert8.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert8.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert8.artist);
        System.out.println("The liveConcert genre is: " + liveConcert8.genre);
        System.out.println("The liveConcert venue is: " + liveConcert8.venue);
        System.out.println("The liveConcert city is: " + liveConcert8.city);
        System.out.println("The liveConcert country is: " + liveConcert8.country);
        System.out.println("The liveConcert date is: " + liveConcert8.date);
        System.out.println("The liveConcert time is: " + liveConcert8.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert8.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert8.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert8.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert8.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert8.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert8.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert8.contactNumber);
		
		Concert liveConcert9 = new Concert();
        liveConcert9.concertID = "CON7890";
        liveConcert9.artist = "Taylor Swift";
        liveConcert9.genre = "Pop";
        liveConcert9.venue = "Wembley Stadium";
        liveConcert9.city = "London";
        liveConcert9.country = "UK";
        liveConcert9.date = "2024-09-15";
        liveConcert9.time = "19:00";
        liveConcert9.durationMinutes = 120;
        liveConcert9.ticketPrice = 150.00;
        liveConcert9.totalTickets = 80000;
        liveConcert9.availableTickets = 5000;
        liveConcert9.isOutdoor = true;
        liveConcert9.organizer = "Music Events Ltd.";
        liveConcert9.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert9.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert9.artist);
        System.out.println("The liveConcert genre is: " + liveConcert9.genre);
        System.out.println("The liveConcert venue is: " + liveConcert9.venue);
        System.out.println("The liveConcert city is: " + liveConcert9.city);
        System.out.println("The liveConcert country is: " + liveConcert9.country);
        System.out.println("The liveConcert date is: " + liveConcert9.date);
        System.out.println("The liveConcert time is: " + liveConcert9.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert9.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert9.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert9.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert9.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert9.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert9.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert9.contactNumber);
		
		Concert liveConcert10 = new Concert();
        liveConcert10.concertID = "CON7890";
        liveConcert10.artist = "Taylor Swift";
        liveConcert10.genre = "Pop";
        liveConcert10.venue = "Wembley Stadium";
        liveConcert10.city = "London";
        liveConcert10.country = "UK";
        liveConcert10.date = "2024-09-15";
        liveConcert10.time = "19:00";
        liveConcert10.durationMinutes = 120;
        liveConcert10.ticketPrice = 150.00;
        liveConcert10.totalTickets = 80000;
        liveConcert10.availableTickets = 5000;
        liveConcert10.isOutdoor = true;
        liveConcert10.organizer = "Music Events Ltd.";
        liveConcert10.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert10.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert10.artist);
        System.out.println("The liveConcert genre is: " + liveConcert10.genre);
        System.out.println("The liveConcert venue is: " + liveConcert10.venue);
        System.out.println("The liveConcert city is: " + liveConcert10.city);
        System.out.println("The liveConcert country is: " + liveConcert10.country);
        System.out.println("The liveConcert date is: " + liveConcert10.date);
        System.out.println("The liveConcert time is: " + liveConcert10.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert10.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert10.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert10.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert10.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert10.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert10.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert10.contactNumber);
		
		Concert liveConcert11 = new Concert();
        liveConcert11.concertID = "CON7890";
        liveConcert11.artist = "Taylor Swift";
        liveConcert11.genre = "Pop";
        liveConcert11.venue = "Wembley Stadium";
        liveConcert11.city = "London";
        liveConcert11.country = "UK";
        liveConcert11.date = "2024-09-15";
        liveConcert11.time = "19:00";
        liveConcert11.durationMinutes = 120;
        liveConcert11.ticketPrice = 150.00;
        liveConcert11.totalTickets = 80000;
        liveConcert11.availableTickets = 5000;
        liveConcert11.isOutdoor = true;
        liveConcert11.organizer = "Music Events Ltd.";
        liveConcert10.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert11.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert11.artist);
        System.out.println("The liveConcert genre is: " + liveConcert11.genre);
        System.out.println("The liveConcert venue is: " + liveConcert11.venue);
        System.out.println("The liveConcert city is: " + liveConcert11.city);
        System.out.println("The liveConcert country is: " + liveConcert11.country);
        System.out.println("The liveConcert date is: " + liveConcert11.date);
        System.out.println("The liveConcert time is: " + liveConcert11.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert11.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert11.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert11.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert11.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert11.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert11.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert11.contactNumber);
		
		Concert liveConcert12 = new Concert();
        liveConcert12.concertID = "CON7890";
        liveConcert12.artist = "Taylor Swift";
        liveConcert12.genre = "Pop";
        liveConcert12.venue = "Wembley Stadium";
        liveConcert12.city = "London";
        liveConcert12.country = "UK";
        liveConcert12.date = "2024-09-15";
        liveConcert12.time = "19:00";
        liveConcert12.durationMinutes = 120;
        liveConcert12.ticketPrice = 150.00;
        liveConcert12.totalTickets = 80000;
        liveConcert12.availableTickets = 5000;
        liveConcert12.isOutdoor = true;
        liveConcert12.organizer = "Music Events Ltd.";
        liveConcert12.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert12.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert12.artist);
        System.out.println("The liveConcert genre is: " + liveConcert12.genre);
        System.out.println("The liveConcert venue is: " + liveConcert12.venue);
        System.out.println("The liveConcert city is: " + liveConcert12.city);
        System.out.println("The liveConcert country is: " + liveConcert12.country);
        System.out.println("The liveConcert date is: " + liveConcert12.date);
        System.out.println("The liveConcert time is: " + liveConcert12.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert12.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert12.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert12.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert12.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert12.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert12.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert12.contactNumber);
		
		Concert liveConcert13 = new Concert();
        liveConcert13.concertID = "CON7890";
        liveConcert13.artist = "Taylor Swift";
        liveConcert13.genre = "Pop";
        liveConcert13.venue = "Wembley Stadium";
        liveConcert13.city = "London";
        liveConcert13.country = "UK";
        liveConcert13.date = "2024-09-15";
        liveConcert13.time = "19:00";
        liveConcert13.durationMinutes = 120;
        liveConcert13.ticketPrice = 150.00;
        liveConcert13.totalTickets = 80000;
        liveConcert13.availableTickets = 5000;
        liveConcert13.isOutdoor = true;
        liveConcert13.organizer = "Music Events Ltd.";
        liveConcert13.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert13.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert13.artist);
        System.out.println("The liveConcert genre is: " + liveConcert13.genre);
        System.out.println("The liveConcert venue is: " + liveConcert13.venue);
        System.out.println("The liveConcert city is: " + liveConcert13.city);
        System.out.println("The liveConcert country is: " + liveConcert13.country);
        System.out.println("The liveConcert date is: " + liveConcert13.date);
        System.out.println("The liveConcert time is: " + liveConcert13.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert13.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert13.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert13.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert13.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert13.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert13.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert13.contactNumber);
		
		Concert liveConcert14 = new Concert();
        liveConcert14.concertID = "CON7890";
        liveConcert14.artist = "Taylor Swift";
        liveConcert14.genre = "Pop";
        liveConcert14.venue = "Wembley Stadium";
        liveConcert14.city = "London";
        liveConcert14.country = "UK";
        liveConcert14.date = "2024-09-15";
        liveConcert14.time = "19:00";
        liveConcert14.durationMinutes = 120;
        liveConcert14.ticketPrice = 150.00;
        liveConcert14.totalTickets = 80000;
        liveConcert14.availableTickets = 5000;
        liveConcert14.isOutdoor = true;
        liveConcert14.organizer = "Music Events Ltd.";
        liveConcert14.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert14.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert14.artist);
        System.out.println("The liveConcert genre is: " + liveConcert14.genre);
        System.out.println("The liveConcert venue is: " + liveConcert14.venue);
        System.out.println("The liveConcert city is: " + liveConcert14.city);
        System.out.println("The liveConcert country is: " + liveConcert14.country);
        System.out.println("The liveConcert date is: " + liveConcert14.date);
        System.out.println("The liveConcert time is: " + liveConcert14.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert14.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert14.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert14.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert14.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert14.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert14.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert14.contactNumber);
		
		Concert liveConcert15 = new Concert();
        liveConcert15.concertID = "CON7890";
        liveConcert15.artist = "Taylor Swift";
        liveConcert15.genre = "Pop";
        liveConcert15.venue = "Wembley Stadium";
        liveConcert15.city = "London";
        liveConcert15.country = "UK";
        liveConcert15.date = "2024-09-15";
        liveConcert15.time = "19:00";
        liveConcert15.durationMinutes = 120;
        liveConcert15.ticketPrice = 150.00;
        liveConcert15.totalTickets = 80000;
        liveConcert15.availableTickets = 5000;
        liveConcert15.isOutdoor = true;
        liveConcert15.organizer = "Music Events Ltd.";
        liveConcert15.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert15.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert15.artist);
        System.out.println("The liveConcert genre is: " + liveConcert15.genre);
        System.out.println("The liveConcert venue is: " + liveConcert15.venue);
        System.out.println("The liveConcert city is: " + liveConcert15.city);
        System.out.println("The liveConcert country is: " + liveConcert15.country);
        System.out.println("The liveConcert date is: " + liveConcert15.date);
        System.out.println("The liveConcert time is: " + liveConcert15.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert15.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert15.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert15.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert15.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert15.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert15.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert15.contactNumber);
		
		Concert liveConcert16 = new Concert();
        liveConcert16.concertID = "CON7890";
        liveConcert16.artist = "Taylor Swift";
        liveConcert16.genre = "Pop";
        liveConcert16.venue = "Wembley Stadium";
        liveConcert16.city = "London";
        liveConcert16.country = "UK";
        liveConcert16.date = "2024-09-15";
        liveConcert16.time = "19:00";
        liveConcert16.durationMinutes = 120;
        liveConcert16.ticketPrice = 150.00;
        liveConcert16.totalTickets = 80000;
        liveConcert16.availableTickets = 5000;
        liveConcert16.isOutdoor = true;
        liveConcert16.organizer = "Music Events Ltd.";
        liveConcert16.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert16.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert16.artist);
        System.out.println("The liveConcert genre is: " + liveConcert16.genre);
        System.out.println("The liveConcert venue is: " + liveConcert16.venue);
        System.out.println("The liveConcert city is: " + liveConcert16.city);
        System.out.println("The liveConcert country is: " + liveConcert16.country);
        System.out.println("The liveConcert date is: " + liveConcert16.date);
        System.out.println("The liveConcert time is: " + liveConcert16.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert16.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert16.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert16.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert16.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert16.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert16.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert16.contactNumber);
		
		Concert liveConcert17 = new Concert();
        liveConcert17.concertID = "CON7890";
        liveConcert17.artist = "Taylor Swift";
        liveConcert17.genre = "Pop";
        liveConcert17.venue = "Wembley Stadium";
        liveConcert17.city = "London";
        liveConcert17.country = "UK";
        liveConcert17.date = "2024-09-15";
        liveConcert17.time = "19:00";
        liveConcert17.durationMinutes = 120;
        liveConcert17.ticketPrice = 150.00;
        liveConcert17.totalTickets = 80000;
        liveConcert17.availableTickets = 5000;
        liveConcert17.isOutdoor = true;
        liveConcert17.organizer = "Music Events Ltd.";
        liveConcert17.contactNumber = "+44 20 1234 5678";
        System.out.println("The liveConcert concertID is: " + liveConcert17.concertID);
        System.out.println("The liveConcert artist is: " + liveConcert17.artist);
        System.out.println("The liveConcert genre is: " + liveConcert17.genre);
        System.out.println("The liveConcert venue is: " + liveConcert17.venue);
        System.out.println("The liveConcert city is: " + liveConcert17.city);
        System.out.println("The liveConcert country is: " + liveConcert17.country);
        System.out.println("The liveConcert date is: " + liveConcert17.date);
        System.out.println("The liveConcert time is: " + liveConcert17.time);
        System.out.println("The liveConcert durationMinutes is: " + liveConcert17.durationMinutes);
        System.out.println("The liveConcert ticketPrice is: " + liveConcert17.ticketPrice);
        System.out.println("The liveConcert totalTickets is: " + liveConcert17.totalTickets);
        System.out.println("The liveConcert availableTickets is: " + liveConcert17.availableTickets);
        System.out.println("The liveConcert isOutdoor is: " + liveConcert17.isOutdoor);
        System.out.println("The liveConcert organizer is: " + liveConcert17.organizer);
        System.out.println("The liveConcert contactNumber is: " + liveConcert17.contactNumber);
    }
}