public class Course01Runner
{
	public static void main(String args[])
	{
		new Course01Runner();
		
		Course01 course1 = new Course01();
		course1.courseName = "java";
		course1.courseCode = "18cs73";
		course1.credits = 3;
		course1.instructor = "Nagaraj T";
		course1.department = "CSE";
		course1.durationWeeks = 12;
		course1.schedule = "Mon,Wed,Fri";
		course1.location = "RoomNo-3037";
		course1.enrolledStudents = 65;
		course1.isMandatory = true;
		course1.syllabus = "5 Modules";
		course1.isOnline = false;
		course1.courseFee = 500;
		System.out.println("The Course name is:"+course1.courseName);
		System.out.println("The Course Code is:"+course1.courseCode);
		System.out.println("The Course credits is:"+course1.credits);
		System.out.println("The Course instructor is:"+course1.instructor);
		System.out.println("The Course department is:"+course1.department);
		System.out.println("The Course durationWeeks is:"+course1.durationWeeks);
		System.out.println("The Course schedule is:"+course1.schedule);
		System.out.println("The Course location is:"+course1.location);
		System.out.println("The Course enrolledStudents is:"+course1.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course1.isMandatory);
		System.out.println("The Course syllabus is:"+course1.syllabus);
		System.out.println("The Course isOnline is:"+course1.isOnline);
		System.out.println("The Course courseFee is:"+course1.courseFee);
		
		Course01 course2 = new Course01();
		course2.courseName = "java";
		course2.courseCode = "18cs73";
		course2.credits = 3;
		course2.instructor = "Nagaraj T";
		course2.department = "CSE";
		course2.durationWeeks = 12;
		course2.schedule = "Mon,Wed,Fri";
		course2.location = "RoomNo-3037";
		course2.enrolledStudents = 65;
		course2.isMandatory = true;
		course2.syllabus = "5 Modules";
		course2.isOnline = false;
		course2.courseFee = 500;
		System.out.println("The Course name is:"+course2.courseName);
		System.out.println("The Course Code is:"+course2.courseCode);
		System.out.println("The Course credits is:"+course2.credits);
		System.out.println("The Course instructor is:"+course2.instructor);
		System.out.println("The Course department is:"+course2.department);
		System.out.println("The Course durationWeeks is:"+course2.durationWeeks);
		System.out.println("The Course schedule is:"+course2.schedule);
		System.out.println("The Course location is:"+course2.location);
		System.out.println("The Course enrolledStudents is:"+course2.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course2.isMandatory);
		System.out.println("The Course syllabus is:"+course2.syllabus);
		System.out.println("The Course isOnline is:"+course2.isOnline);
		System.out.println("The Course courseFee is:"+course2.courseFee);
		
		Course01 course3 = new Course01();
		course3.courseName = "java";
		course3.courseCode = "18cs73";
		course3.credits = 3;
		course3.instructor = "Nagaraj T";
		course3.department = "CSE";
		course3.durationWeeks = 12;
		course3.schedule = "Mon,Wed,Fri";
		course3.location = "RoomNo-3037";
		course3.enrolledStudents = 65;
		course3.isMandatory = true;
		course3.syllabus = "5 Modules";
		course3.isOnline = false;
		course3.courseFee = 500;
		System.out.println("The Course name is:"+course3.courseName);
		System.out.println("The Course Code is:"+course3.courseCode);
		System.out.println("The Course credits is:"+course3.credits);
		System.out.println("The Course instructor is:"+course3.instructor);
		System.out.println("The Course department is:"+course3.department);
		System.out.println("The Course durationWeeks is:"+course3.durationWeeks);
		System.out.println("The Course schedule is:"+course3.schedule);
		System.out.println("The Course location is:"+course3.location);
		System.out.println("The Course enrolledStudents is:"+course3.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course3.isMandatory);
		System.out.println("The Course syllabus is:"+course3.syllabus);
		System.out.println("The Course isOnline is:"+course3.isOnline);
		System.out.println("The Course courseFee is:"+course3.courseFee);
		
		Course01 course4 = new Course01();
		course4.courseName = "java";
		course4.courseCode = "18cs73";
		course4.credits = 3;
		course4.instructor = "Nagaraj T";
		course4.department = "CSE";
		course4.durationWeeks = 12;
		course4.schedule = "Mon,Wed,Fri";
		course4.location = "RoomNo-3037";
		course4.enrolledStudents = 65;
		course4.isMandatory = true;
		course4.syllabus = "5 Modules";
		course4.isOnline = false;
		course4.courseFee = 500;
		System.out.println("The Course name is:"+course4.courseName);
		System.out.println("The Course Code is:"+course4.courseCode);
		System.out.println("The Course credits is:"+course4.credits);
		System.out.println("The Course instructor is:"+course4.instructor);
		System.out.println("The Course department is:"+course4.department);
		System.out.println("The Course durationWeeks is:"+course4.durationWeeks);
		System.out.println("The Course schedule is:"+course4.schedule);
		System.out.println("The Course location is:"+course4.location);
		System.out.println("The Course enrolledStudents is:"+course4.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course4.isMandatory);
		System.out.println("The Course syllabus is:"+course4.syllabus);
		System.out.println("The Course isOnline is:"+course4.isOnline);
		System.out.println("The Course courseFee is:"+course4.courseFee);
		
		Course01 course5 = new Course01();
		course5.courseName = "java";
		course5.courseCode = "18cs73";
		course5.credits = 3;
		course5.instructor = "Nagaraj T";
		course5.department = "CSE";
		course5.durationWeeks = 12;
		course5.schedule = "Mon,Wed,Fri";
		course5.location = "RoomNo-3037";
		course5.enrolledStudents = 65;
		course5.isMandatory = true;
		course5.syllabus = "5 Modules";
		course5.isOnline = false;
		course5.courseFee = 500;
		System.out.println("The Course name is:"+course5.courseName);
		System.out.println("The Course Code is:"+course5.courseCode);
		System.out.println("The Course credits is:"+course5.credits);
		System.out.println("The Course instructor is:"+course5.instructor);
		System.out.println("The Course department is:"+course5.department);
		System.out.println("The Course durationWeeks is:"+course5.durationWeeks);
		System.out.println("The Course schedule is:"+course5.schedule);
		System.out.println("The Course location is:"+course5.location);
		System.out.println("The Course enrolledStudents is:"+course5.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course5.isMandatory);
		System.out.println("The Course syllabus is:"+course5.syllabus);
		System.out.println("The Course isOnline is:"+course5.isOnline);
		System.out.println("The Course courseFee is:"+course5.courseFee);
		
		Course01 course6 = new Course01();
		course6.courseName = "java";
		course6.courseCode = "18cs73";
		course6.credits = 3;
		course6.instructor = "Nagaraj T";
		course6.department = "CSE";
		course6.durationWeeks = 12;
		course6.schedule = "Mon,Wed,Fri";
		course6.location = "RoomNo-3037";
		course6.enrolledStudents = 65;
		course6.isMandatory = true;
		course6.syllabus = "5 Modules";
		course6.isOnline = false;
		course6.courseFee = 500;
		System.out.println("The Course name is:"+course6.courseName);
		System.out.println("The Course Code is:"+course6.courseCode);
		System.out.println("The Course credits is:"+course6.credits);
		System.out.println("The Course instructor is:"+course6.instructor);
		System.out.println("The Course department is:"+course6.department);
		System.out.println("The Course durationWeeks is:"+course6.durationWeeks);
		System.out.println("The Course schedule is:"+course6.schedule);
		System.out.println("The Course location is:"+course6.location);
		System.out.println("The Course enrolledStudents is:"+course6.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course6.isMandatory);
		System.out.println("The Course syllabus is:"+course6.syllabus);
		System.out.println("The Course isOnline is:"+course6.isOnline);
		System.out.println("The Course courseFee is:"+course6.courseFee);
		
		Course01 course7 = new Course01();
		course7.courseName = "java";
		course7.courseCode = "18cs73";
		course7.credits = 3;
		course7.instructor = "Nagaraj T";
		course7.department = "CSE";
		course7.durationWeeks = 12;
		course7.schedule = "Mon,Wed,Fri";
		course7.location = "RoomNo-3037";
		course7.enrolledStudents = 65;
		course7.isMandatory = true;
		course7.syllabus = "5 Modules";
		course7.isOnline = false;
		course7.courseFee = 500;
		System.out.println("The Course name is:"+course7.courseName);
		System.out.println("The Course Code is:"+course7.courseCode);
		System.out.println("The Course credits is:"+course7.credits);
		System.out.println("The Course instructor is:"+course7.instructor);
		System.out.println("The Course department is:"+course7.department);
		System.out.println("The Course durationWeeks is:"+course7.durationWeeks);
		System.out.println("The Course schedule is:"+course7.schedule);
		System.out.println("The Course location is:"+course7.location);
		System.out.println("The Course enrolledStudents is:"+course7.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course7.isMandatory);
		System.out.println("The Course syllabus is:"+course7.syllabus);
		System.out.println("The Course isOnline is:"+course7.isOnline);
		System.out.println("The Course courseFee is:"+course7.courseFee);
		
		Course01 course8 = new Course01();
		course8.courseName = "java";
		course8.courseCode = "18cs73";
		course8.credits = 3;
		course8.instructor = "Nagaraj T";
		course8.department = "CSE";
		course8.durationWeeks = 12;
		course8.schedule = "Mon,Wed,Fri";
		course8.location = "RoomNo-3037";
		course8.enrolledStudents = 65;
		course8.isMandatory = true;
		course8.syllabus = "5 Modules";
		course8.isOnline = false;
		course8.courseFee = 500;
		System.out.println("The Course name is:"+course8.courseName);
		System.out.println("The Course Code is:"+course8.courseCode);
		System.out.println("The Course credits is:"+course8.credits);
		System.out.println("The Course instructor is:"+course8.instructor);
		System.out.println("The Course department is:"+course8.department);
		System.out.println("The Course durationWeeks is:"+course8.durationWeeks);
		System.out.println("The Course schedule is:"+course8.schedule);
		System.out.println("The Course location is:"+course8.location);
		System.out.println("The Course enrolledStudents is:"+course8.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course8.isMandatory);
		System.out.println("The Course syllabus is:"+course8.syllabus);
		System.out.println("The Course isOnline is:"+course8.isOnline);
		System.out.println("The Course courseFee is:"+course8.courseFee);
		
		Course01 course9 = new Course01();
		course9.courseName = "java";
		course9.courseCode = "18cs73";
		course9.credits = 3;
		course9.instructor = "Nagaraj T";
		course9.department = "CSE";
		course9.durationWeeks = 12;
		course9.schedule = "Mon,Wed,Fri";
		course9.location = "RoomNo-3037";
		course9.enrolledStudents = 65;
		course9.isMandatory = true;
		course9.syllabus = "5 Modules";
		course9.isOnline = false;
		course9.courseFee = 500;
		System.out.println("The Course name is:"+course9.courseName);
		System.out.println("The Course Code is:"+course9.courseCode);
		System.out.println("The Course credits is:"+course9.credits);
		System.out.println("The Course instructor is:"+course9.instructor);
		System.out.println("The Course department is:"+course9.department);
		System.out.println("The Course durationWeeks is:"+course9.durationWeeks);
		System.out.println("The Course schedule is:"+course9.schedule);
		System.out.println("The Course location is:"+course9.location);
		System.out.println("The Course enrolledStudents is:"+course9.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course9.isMandatory);
		System.out.println("The Course syllabus is:"+course9.syllabus);
		System.out.println("The Course isOnline is:"+course9.isOnline);
		System.out.println("The Course courseFee is:"+course9.courseFee);
		
		Course01 course10 = new Course01();
		course10.courseName = "java";
		course10.courseCode = "18cs73";
		course10.credits = 3;
		course10.instructor = "Nagaraj T";
		course10.department = "CSE";
		course10.durationWeeks = 12;
		course10.schedule = "Mon,Wed,Fri";
		course10.location = "RoomNo-3037";
		course10.enrolledStudents = 65;
		course10.isMandatory = true;
		course10.syllabus = "5 Modules";
		course10.isOnline = false;
		course10.courseFee = 500;
		System.out.println("The Course name is:"+course10.courseName);
		System.out.println("The Course Code is:"+course10.courseCode);
		System.out.println("The Course credits is:"+course10.credits);
		System.out.println("The Course instructor is:"+course10.instructor);
		System.out.println("The Course department is:"+course10.department);
		System.out.println("The Course durationWeeks is:"+course10.durationWeeks);
		System.out.println("The Course schedule is:"+course10.schedule);
		System.out.println("The Course location is:"+course10.location);
		System.out.println("The Course enrolledStudents is:"+course10.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course10.isMandatory);
		System.out.println("The Course syllabus is:"+course10.syllabus);
		System.out.println("The Course isOnline is:"+course10.isOnline);
		System.out.println("The Course courseFee is:"+course10.courseFee);
		
		Course01 course11 = new Course01();
		course11.courseName = "java";
		course11.courseCode = "18cs73";
		course11.credits = 3;
		course11.instructor = "Nagaraj T";
		course11.department = "CSE";
		course11.durationWeeks = 12;
		course11.schedule = "Mon,Wed,Fri";
		course11.location = "RoomNo-3037";
		course11.enrolledStudents = 65;
		course11.isMandatory = true;
		course11.syllabus = "5 Modules";
		course11.isOnline = false;
		course11.courseFee = 500;
		System.out.println("The Course name is:"+course11.courseName);
		System.out.println("The Course Code is:"+course11.courseCode);
		System.out.println("The Course credits is:"+course11.credits);
		System.out.println("The Course instructor is:"+course11.instructor);
		System.out.println("The Course department is:"+course11.department);
		System.out.println("The Course durationWeeks is:"+course11.durationWeeks);
		System.out.println("The Course schedule is:"+course11.schedule);
		System.out.println("The Course location is:"+course11.location);
		System.out.println("The Course enrolledStudents is:"+course11.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course11.isMandatory);
		System.out.println("The Course syllabus is:"+course11.syllabus);
		System.out.println("The Course isOnline is:"+course11.isOnline);
		System.out.println("The Course courseFee is:"+course11.courseFee);
		
		Course01 course12 = new Course01();
		course12.courseName = "java";
		course12.courseCode = "18cs73";
		course12.credits = 3;
		course12.instructor = "Nagaraj T";
		course12.department = "CSE";
		course12.durationWeeks = 12;
		course12.schedule = "Mon,Wed,Fri";
		course12.location = "RoomNo-3037";
		course12.enrolledStudents = 65;
		course12.isMandatory = true;
		course12.syllabus = "5 Modules";
		course12.isOnline = false;
		course12.courseFee = 500;
		System.out.println("The Course name is:"+course12.courseName);
		System.out.println("The Course Code is:"+course12.courseCode);
		System.out.println("The Course credits is:"+course12.credits);
		System.out.println("The Course instructor is:"+course12.instructor);
		System.out.println("The Course department is:"+course12.department);
		System.out.println("The Course durationWeeks is:"+course12.durationWeeks);
		System.out.println("The Course schedule is:"+course12.schedule);
		System.out.println("The Course location is:"+course12.location);
		System.out.println("The Course enrolledStudents is:"+course12.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course12.isMandatory);
		System.out.println("The Course syllabus is:"+course12.syllabus);
		System.out.println("The Course isOnline is:"+course12.isOnline);
		System.out.println("The Course courseFee is:"+course12.courseFee);
		
		Course01 course13 = new Course01();
		course13.courseName = "java";
		course13.courseCode = "18cs73";
		course13.credits = 3;
		course13.instructor = "Nagaraj T";
		course13.department = "CSE";
		course13.durationWeeks = 12;
		course13.schedule = "Mon,Wed,Fri";
		course13.location = "RoomNo-3037";
		course13.enrolledStudents = 65;
		course13.isMandatory = true;
		course13.syllabus = "5 Modules";
		course13.isOnline = false;
		course13.courseFee = 500;
		System.out.println("The Course name is:"+course13.courseName);
		System.out.println("The Course Code is:"+course13.courseCode);
		System.out.println("The Course credits is:"+course13.credits);
		System.out.println("The Course instructor is:"+course13.instructor);
		System.out.println("The Course department is:"+course13.department);
		System.out.println("The Course durationWeeks is:"+course13.durationWeeks);
		System.out.println("The Course schedule is:"+course13.schedule);
		System.out.println("The Course location is:"+course13.location);
		System.out.println("The Course enrolledStudents is:"+course13.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course13.isMandatory);
		System.out.println("The Course syllabus is:"+course13.syllabus);
		System.out.println("The Course isOnline is:"+course13.isOnline);
		System.out.println("The Course courseFee is:"+course13.courseFee);
		
		Course01 course14 = new Course01();
		course14.courseName = "java";
		course14.courseCode = "18cs73";
		course14.credits = 3;
		course14.instructor = "Nagaraj T";
		course14.department = "CSE";
		course14.durationWeeks = 12;
		course14.schedule = "Mon,Wed,Fri";
		course14.location = "RoomNo-3037";
		course14.enrolledStudents = 65;
		course14.isMandatory = true;
		course14.syllabus = "5 Modules";
		course14.isOnline = false;
		course14.courseFee = 500;
		System.out.println("The Course name is:"+course14.courseName);
		System.out.println("The Course Code is:"+course14.courseCode);
		System.out.println("The Course credits is:"+course14.credits);
		System.out.println("The Course instructor is:"+course14.instructor);
		System.out.println("The Course department is:"+course14.department);
		System.out.println("The Course durationWeeks is:"+course14.durationWeeks);
		System.out.println("The Course schedule is:"+course14.schedule);
		System.out.println("The Course location is:"+course14.location);
		System.out.println("The Course enrolledStudents is:"+course14.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course14.isMandatory);
		System.out.println("The Course syllabus is:"+course14.syllabus);
		System.out.println("The Course isOnline is:"+course14.isOnline);
		System.out.println("The Course courseFee is:"+course14.courseFee);
		
		Course01 course15 = new Course01();
		course15.courseName = "java";
		course15.courseCode = "18cs73";
		course15.credits = 3;
		course15.instructor = "Nagaraj T";
		course15.department = "CSE";
		course15.durationWeeks = 12;
		course15.schedule = "Mon,Wed,Fri";
		course15.location = "RoomNo-3037";
		course15.enrolledStudents = 65;
		course15.isMandatory = true;
		course15.syllabus = "5 Modules";
		course15.isOnline = false;
		course15.courseFee = 500;
		System.out.println("The Course name is:"+course15.courseName);
		System.out.println("The Course Code is:"+course15.courseCode);
		System.out.println("The Course credits is:"+course15.credits);
		System.out.println("The Course instructor is:"+course15.instructor);
		System.out.println("The Course department is:"+course15.department);
		System.out.println("The Course durationWeeks is:"+course15.durationWeeks);
		System.out.println("The Course schedule is:"+course15.schedule);
		System.out.println("The Course location is:"+course15.location);
		System.out.println("The Course enrolledStudents is:"+course15.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course15.isMandatory);
		System.out.println("The Course syllabus is:"+course15.syllabus);
		System.out.println("The Course isOnline is:"+course15.isOnline);
		System.out.println("The Course courseFee is:"+course15.courseFee);
		
		Course01 course16 = new Course01();
		course16.courseName = "java";
		course16.courseCode = "18cs73";
		course16.credits = 3;
		course16.instructor = "Nagaraj T";
		course16.department = "CSE";
		course16.durationWeeks = 12;
		course16.schedule = "Mon,Wed,Fri";
		course16.location = "RoomNo-3037";
		course16.enrolledStudents = 65;
		course16.isMandatory = true;
		course16.syllabus = "5 Modules";
		course16.isOnline = false;
		course16.courseFee = 500;
		System.out.println("The Course name is:"+course16.courseName);
		System.out.println("The Course Code is:"+course16.courseCode);
		System.out.println("The Course credits is:"+course16.credits);
		System.out.println("The Course instructor is:"+course16.instructor);
		System.out.println("The Course department is:"+course16.department);
		System.out.println("The Course durationWeeks is:"+course16.durationWeeks);
		System.out.println("The Course schedule is:"+course16.schedule);
		System.out.println("The Course location is:"+course16.location);
		System.out.println("The Course enrolledStudents is:"+course16.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course16.isMandatory);
		System.out.println("The Course syllabus is:"+course16.syllabus);
		System.out.println("The Course isOnline is:"+course16.isOnline);
		System.out.println("The Course courseFee is:"+course16.courseFee);
		
		Course01 course17 = new Course01();
		course17.courseName = "java";
		course17.courseCode = "18cs73";
		course17.credits = 3;
		course17.instructor = "Nagaraj T";
		course17.department = "CSE";
		course17.durationWeeks = 12;
		course17.schedule = "Mon,Wed,Fri";
		course17.location = "RoomNo-3037";
		course17.enrolledStudents = 65;
		course17.isMandatory = true;
		course17.syllabus = "5 Modules";
		course17.isOnline = false;
		course17.courseFee = 500;
		System.out.println("The Course name is:"+course17.courseName);
		System.out.println("The Course Code is:"+course17.courseCode);
		System.out.println("The Course credits is:"+course17.credits);
		System.out.println("The Course instructor is:"+course17.instructor);
		System.out.println("The Course department is:"+course17.department);
		System.out.println("The Course durationWeeks is:"+course17.durationWeeks);
		System.out.println("The Course schedule is:"+course17.schedule);
		System.out.println("The Course location is:"+course17.location);
		System.out.println("The Course enrolledStudents is:"+course17.enrolledStudents);
		System.out.println("The Course isMandatory is:"+course17.isMandatory);
		System.out.println("The Course syllabus is:"+course17.syllabus);
		System.out.println("The Course isOnline is:"+course17.isOnline);
		System.out.println("The Course courseFee is:"+course17.courseFee);
	}
}