public class CruiseRunner 
{
	public static void main(String args[]) 
	{
        new CruiseRunner();

        Cruise luxury1 = new Cruise();
        luxury1.cruiseID = "CRU5678";
        luxury1.cruiseLine = "Royal Caribbean";
        luxury1.departurePort = "Miami";
        luxury1.arrivalPort = "Bahamas";
        luxury1.departureDate = "2024-08-01";
        luxury1.arrivalDate = "2024-08-07";
        luxury1.durationDays = 6;
        luxury1.cabinType = "Suite";
        luxury1.shipType = "Luxury Liner";
        luxury1.totalCabins = 1000;
        luxury1.availableCabins = 200;
        luxury1.isRoundTrip = true;
        luxury1.dock = "Dock 5";
        luxury1.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury1.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury1.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury1.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury1.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury1.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury1.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury1.durationDays);
        System.out.println("The luxury cabinType is: " + luxury1.cabinType);
        System.out.println("The luxury shipType is: " + luxury1.shipType);
        System.out.println("The luxury totalCabins is: " + luxury1.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury1.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury1.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury1.dock);
        System.out.println("The luxury terminal is: " + luxury1.terminal);
		
		 Cruise luxury2 = new Cruise();
        luxury2.cruiseID = "CRU5678";
        luxury2.cruiseLine = "Royal Caribbean";
        luxury2.departurePort = "Miami";
        luxury2.arrivalPort = "Bahamas";
        luxury2.departureDate = "2024-08-01";
        luxury2.arrivalDate = "2024-08-07";
        luxury2.durationDays = 6;
        luxury2.cabinType = "Suite";
        luxury2.shipType = "Luxury Liner";
        luxury2.totalCabins = 1000;
        luxury2.availableCabins = 200;
        luxury2.isRoundTrip = true;
        luxury2.dock = "Dock 5";
        luxury2.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury2.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury2.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury2.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury2.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury2.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury2.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury2.durationDays);
        System.out.println("The luxury cabinType is: " + luxury2.cabinType);
        System.out.println("The luxury shipType is: " + luxury2.shipType);
        System.out.println("The luxury totalCabins is: " + luxury2.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury2.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury2.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury2.dock);
        System.out.println("The luxury terminal is: " + luxury2.terminal);
		
		Cruise luxury3 = new Cruise();
        luxury3.cruiseID = "CRU5678";
        luxury3.cruiseLine = "Royal Caribbean";
        luxury3.departurePort = "Miami";
        luxury3.arrivalPort = "Bahamas";
        luxury3.departureDate = "2024-08-01";
        luxury3.arrivalDate = "2024-08-07";
        luxury3.durationDays = 6;
        luxury3.cabinType = "Suite";
        luxury3.shipType = "Luxury Liner";
        luxury3.totalCabins = 1000;
        luxury3.availableCabins = 200;
        luxury3.isRoundTrip = true;
        luxury3.dock = "Dock 5";
        luxury3.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury3.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury3.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury3.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury3.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury3.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury3.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury3.durationDays);
        System.out.println("The luxury cabinType is: " + luxury3.cabinType);
        System.out.println("The luxury shipType is: " + luxury3.shipType);
        System.out.println("The luxury totalCabins is: " + luxury3.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury3.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury3.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury3.dock);
        System.out.println("The luxury terminal is: " + luxury3.terminal);
		
		Cruise luxury4 = new Cruise();
        luxury4.cruiseID = "CRU5678";
        luxury4.cruiseLine = "Royal Caribbean";
        luxury4.departurePort = "Miami";
        luxury4.arrivalPort = "Bahamas";
        luxury4.departureDate = "2024-08-01";
        luxury4.arrivalDate = "2024-08-07";
        luxury4.durationDays = 6;
        luxury4.cabinType = "Suite";
        luxury4.shipType = "Luxury Liner";
        luxury4.totalCabins = 1000;
        luxury4.availableCabins = 200;
        luxury4.isRoundTrip = true;
        luxury4.dock = "Dock 5";
        luxury4.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury4.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury4.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury4.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury4.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury4.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury4.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury4.durationDays);
        System.out.println("The luxury cabinType is: " + luxury4.cabinType);
        System.out.println("The luxury shipType is: " + luxury4.shipType);
        System.out.println("The luxury totalCabins is: " + luxury4.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury4.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury4.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury4.dock);
        System.out.println("The luxury terminal is: " + luxury4.terminal);
		
		Cruise luxury5 = new Cruise();
        luxury5.cruiseID = "CRU5678";
        luxury5.cruiseLine = "Royal Caribbean";
        luxury5.departurePort = "Miami";
        luxury5.arrivalPort = "Bahamas";
        luxury5.departureDate = "2024-08-01";
        luxury5.arrivalDate = "2024-08-07";
        luxury5.durationDays = 6;
        luxury5.cabinType = "Suite";
        luxury5.shipType = "Luxury Liner";
        luxury5.totalCabins = 1000;
        luxury5.availableCabins = 200;
        luxury5.isRoundTrip = true;
        luxury5.dock = "Dock 5";
        luxury5.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury5.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury5.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury5.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury5.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury5.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury5.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury5.durationDays);
        System.out.println("The luxury cabinType is: " + luxury5.cabinType);
        System.out.println("The luxury shipType is: " + luxury5.shipType);
        System.out.println("The luxury totalCabins is: " + luxury5.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury5.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury5.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury5.dock);
        System.out.println("The luxury terminal is: " + luxury5.terminal);
		
		Cruise luxury6 = new Cruise();
        luxury6.cruiseID = "CRU5678";
        luxury6.cruiseLine = "Royal Caribbean";
        luxury6.departurePort = "Miami";
        luxury6.arrivalPort = "Bahamas";
        luxury6.departureDate = "2024-08-01";
        luxury6.arrivalDate = "2024-08-07";
        luxury6.durationDays = 6;
        luxury6.cabinType = "Suite";
        luxury6.shipType = "Luxury Liner";
        luxury6.totalCabins = 1000;
        luxury6.availableCabins = 200;
        luxury6.isRoundTrip = true;
        luxury6.dock = "Dock 5";
        luxury6.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury6.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury6.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury6.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury6.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury6.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury6.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury6.durationDays);
        System.out.println("The luxury cabinType is: " + luxury6.cabinType);
        System.out.println("The luxury shipType is: " + luxury6.shipType);
        System.out.println("The luxury totalCabins is: " + luxury6.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury6.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury6.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury6.dock);
        System.out.println("The luxury terminal is: " + luxury6.terminal);
		
		Cruise luxury7 = new Cruise();
        luxury7.cruiseID = "CRU5678";
        luxury7.cruiseLine = "Royal Caribbean";
        luxury7.departurePort = "Miami";
        luxury7.arrivalPort = "Bahamas";
        luxury7.departureDate = "2024-08-01";
        luxury7.arrivalDate = "2024-08-07";
        luxury7.durationDays = 6;
        luxury7.cabinType = "Suite";
        luxury7.shipType = "Luxury Liner";
        luxury7.totalCabins = 1000;
        luxury7.availableCabins = 200;
        luxury7.isRoundTrip = true;
        luxury7.dock = "Dock 5";
        luxury7.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury7.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury7.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury7.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury7.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury7.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury7.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury7.durationDays);
        System.out.println("The luxury cabinType is: " + luxury7.cabinType);
        System.out.println("The luxury shipType is: " + luxury7.shipType);
        System.out.println("The luxury totalCabins is: " + luxury7.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury7.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury7.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury7.dock);
        System.out.println("The luxury terminal is: " + luxury7.terminal);
		
		Cruise luxury8 = new Cruise();
        luxury8.cruiseID = "CRU5678";
        luxury8.cruiseLine = "Royal Caribbean";
        luxury8.departurePort = "Miami";
        luxury8.arrivalPort = "Bahamas";
        luxury8.departureDate = "2024-08-01";
        luxury8.arrivalDate = "2024-08-07";
        luxury8.durationDays = 6;
        luxury8.cabinType = "Suite";
        luxury8.shipType = "Luxury Liner";
        luxury8.totalCabins = 1000;
        luxury8.availableCabins = 200;
        luxury8.isRoundTrip = true;
        luxury8.dock = "Dock 5";
        luxury8.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury8.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury8.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury8.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury8.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury8.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury8.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury8.durationDays);
        System.out.println("The luxury cabinType is: " + luxury8.cabinType);
        System.out.println("The luxury shipType is: " + luxury8.shipType);
        System.out.println("The luxury totalCabins is: " + luxury8.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury8.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury8.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury8.dock);
        System.out.println("The luxury terminal is: " + luxury8.terminal);
		
		Cruise luxury9 = new Cruise();
        luxury9.cruiseID = "CRU5678";
        luxury9.cruiseLine = "Royal Caribbean";
        luxury9.departurePort = "Miami";
        luxury9.arrivalPort = "Bahamas";
        luxury9.departureDate = "2024-08-01";
        luxury9.arrivalDate = "2024-08-07";
        luxury9.durationDays = 6;
        luxury9.cabinType = "Suite";
        luxury9.shipType = "Luxury Liner";
        luxury9.totalCabins = 1000;
        luxury9.availableCabins = 200;
        luxury9.isRoundTrip = true;
        luxury9.dock = "Dock 5";
        luxury9.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury9.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury9.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury9.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury9.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury9.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury9.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury9.durationDays);
        System.out.println("The luxury cabinType is: " + luxury9.cabinType);
        System.out.println("The luxury shipType is: " + luxury9.shipType);
        System.out.println("The luxury totalCabins is: " + luxury9.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury9.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury9.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury9.dock);
        System.out.println("The luxury terminal is: " + luxury9.terminal);
		
		Cruise luxury10 = new Cruise();
        luxury10.cruiseID = "CRU5678";
        luxury10.cruiseLine = "Royal Caribbean";
        luxury10.departurePort = "Miami";
        luxury10.arrivalPort = "Bahamas";
        luxury10.departureDate = "2024-08-01";
        luxury10.arrivalDate = "2024-08-07";
        luxury10.durationDays = 6;
        luxury10.cabinType = "Suite";
        luxury10.shipType = "Luxury Liner";
        luxury10.totalCabins = 1000;
        luxury10.availableCabins = 200;
        luxury10.isRoundTrip = true;
        luxury10.dock = "Dock 5";
        luxury10.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury10.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury10.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury10.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury10.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury10.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury10.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury10.durationDays);
        System.out.println("The luxury cabinType is: " + luxury10.cabinType);
        System.out.println("The luxury shipType is: " + luxury10.shipType);
        System.out.println("The luxury totalCabins is: " + luxury10.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury10.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury10.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury10.dock);
        System.out.println("The luxury terminal is: " + luxury10.terminal);
		
		Cruise luxury11 = new Cruise();
        luxury11.cruiseID = "CRU5678";
        luxury11.cruiseLine = "Royal Caribbean";
        luxury11.departurePort = "Miami";
        luxury11.arrivalPort = "Bahamas";
        luxury11.departureDate = "2024-08-01";
        luxury11.arrivalDate = "2024-08-07";
        luxury11.durationDays = 6;
        luxury11.cabinType = "Suite";
        luxury11.shipType = "Luxury Liner";
        luxury11.totalCabins = 1000;
        luxury11.availableCabins = 200;
        luxury11.isRoundTrip = true;
        luxury11.dock = "Dock 5";
        luxury11.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury11.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury11.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury11.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury11.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury11.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury11.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury11.durationDays);
        System.out.println("The luxury cabinType is: " + luxury11.cabinType);
        System.out.println("The luxury shipType is: " + luxury11.shipType);
        System.out.println("The luxury totalCabins is: " + luxury11.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury11.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury11.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury11.dock);
        System.out.println("The luxury terminal is: " + luxury11.terminal);
		
		Cruise luxury12 = new Cruise();
        luxury12.cruiseID = "CRU5678";
        luxury12.cruiseLine = "Royal Caribbean";
        luxury12.departurePort = "Miami";
        luxury12.arrivalPort = "Bahamas";
        luxury12.departureDate = "2024-08-01";
        luxury12.arrivalDate = "2024-08-07";
        luxury12.durationDays = 6;
        luxury12.cabinType = "Suite";
        luxury12.shipType = "Luxury Liner";
        luxury12.totalCabins = 1000;
        luxury12.availableCabins = 200;
        luxury12.isRoundTrip = true;
        luxury12.dock = "Dock 5";
        luxury12.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury12.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury12.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury12.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury12.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury12.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury12.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury12.durationDays);
        System.out.println("The luxury cabinType is: " + luxury12.cabinType);
        System.out.println("The luxury shipType is: " + luxury12.shipType);
        System.out.println("The luxury totalCabins is: " + luxury12.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury12.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury12.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury12.dock);
        System.out.println("The luxury terminal is: " + luxury12.terminal);
		
		Cruise luxury13 = new Cruise();
        luxury13.cruiseID = "CRU5678";
        luxury13.cruiseLine = "Royal Caribbean";
        luxury13.departurePort = "Miami";
        luxury13.arrivalPort = "Bahamas";
        luxury13.departureDate = "2024-08-01";
        luxury13.arrivalDate = "2024-08-07";
        luxury13.durationDays = 6;
        luxury13.cabinType = "Suite";
        luxury13.shipType = "Luxury Liner";
        luxury13.totalCabins = 1000;
        luxury13.availableCabins = 200;
        luxury13.isRoundTrip = true;
        luxury13.dock = "Dock 5";
        luxury13.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury13.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury13.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury13.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury13.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury13.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury13.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury13.durationDays);
        System.out.println("The luxury cabinType is: " + luxury13.cabinType);
        System.out.println("The luxury shipType is: " + luxury13.shipType);
        System.out.println("The luxury totalCabins is: " + luxury13.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury13.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury13.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury13.dock);
        System.out.println("The luxury terminal is: " + luxury13.terminal);
		
		Cruise luxury14 = new Cruise();
        luxury14.cruiseID = "CRU5678";
        luxury14.cruiseLine = "Royal Caribbean";
        luxury14.departurePort = "Miami";
        luxury14.arrivalPort = "Bahamas";
        luxury14.departureDate = "2024-08-01";
        luxury14.arrivalDate = "2024-08-07";
        luxury14.durationDays = 6;
        luxury14.cabinType = "Suite";
        luxury14.shipType = "Luxury Liner";
        luxury14.totalCabins = 1000;
        luxury14.availableCabins = 200;
        luxury14.isRoundTrip = true;
        luxury14.dock = "Dock 5";
        luxury14.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury14.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury14.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury14.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury14.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury14.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury14.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury14.durationDays);
        System.out.println("The luxury cabinType is: " + luxury14.cabinType);
        System.out.println("The luxury shipType is: " + luxury14.shipType);
        System.out.println("The luxury totalCabins is: " + luxury14.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury14.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury14.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury14.dock);
        System.out.println("The luxury terminal is: " + luxury14.terminal);
		
		Cruise luxury15 = new Cruise();
        luxury15.cruiseID = "CRU5678";
        luxury15.cruiseLine = "Royal Caribbean";
        luxury15.departurePort = "Miami";
        luxury15.arrivalPort = "Bahamas";
        luxury15.departureDate = "2024-08-01";
        luxury15.arrivalDate = "2024-08-07";
        luxury15.durationDays = 6;
        luxury15.cabinType = "Suite";
        luxury15.shipType = "Luxury Liner";
        luxury15.totalCabins = 1000;
        luxury15.availableCabins = 200;
        luxury15.isRoundTrip = true;
        luxury15.dock = "Dock 5";
        luxury15.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury15.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury15.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury15.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury15.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury15.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury15.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury15.durationDays);
        System.out.println("The luxury cabinType is: " + luxury15.cabinType);
        System.out.println("The luxury shipType is: " + luxury15.shipType);
        System.out.println("The luxury totalCabins is: " + luxury15.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury15.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury15.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury15.dock);
        System.out.println("The luxury terminal is: " + luxury15.terminal);
		
		Cruise luxury16 = new Cruise();
        luxury16.cruiseID = "CRU5678";
        luxury16.cruiseLine = "Royal Caribbean";
        luxury16.departurePort = "Miami";
        luxury16.arrivalPort = "Bahamas";
        luxury16.departureDate = "2024-08-01";
        luxury16.arrivalDate = "2024-08-07";
        luxury16.durationDays = 6;
        luxury16.cabinType = "Suite";
        luxury16.shipType = "Luxury Liner";
        luxury16.totalCabins = 1000;
        luxury16.availableCabins = 200;
        luxury16.isRoundTrip = true;
        luxury16.dock = "Dock 5";
        luxury16.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury16.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury16.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury16.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury16.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury16.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury16.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury16.durationDays);
        System.out.println("The luxury cabinType is: " + luxury16.cabinType);
        System.out.println("The luxury shipType is: " + luxury16.shipType);
        System.out.println("The luxury totalCabins is: " + luxury16.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury16.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury16.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury16.dock);
        System.out.println("The luxury terminal is: " + luxury16.terminal);
		
		Cruise luxury17 = new Cruise();
        luxury17.cruiseID = "CRU5678";
        luxury17.cruiseLine = "Royal Caribbean";
        luxury17.departurePort = "Miami";
        luxury17.arrivalPort = "Bahamas";
        luxury17.departureDate = "2024-08-01";
        luxury17.arrivalDate = "2024-08-07";
        luxury17.durationDays = 6;
        luxury17.cabinType = "Suite";
        luxury17.shipType = "Luxury Liner";
        luxury17.totalCabins = 1000;
        luxury17.availableCabins = 200;
        luxury17.isRoundTrip = true;
        luxury17.dock = "Dock 5";
        luxury17.terminal = "Terminal B";
        System.out.println("The luxury cruiseID is: " + luxury17.cruiseID);
        System.out.println("The luxury cruiseLine is: " + luxury17.cruiseLine);
        System.out.println("The luxury departurePort is: " + luxury17.departurePort);
        System.out.println("The luxury arrivalPort is: " + luxury17.arrivalPort);
        System.out.println("The luxury departureDate is: " + luxury17.departureDate);
        System.out.println("The luxury arrivalDate is: " + luxury17.arrivalDate);
        System.out.println("The luxury durationDays is: " + luxury17.durationDays);
        System.out.println("The luxury cabinType is: " + luxury17.cabinType);
        System.out.println("The luxury shipType is: " + luxury17.shipType);
        System.out.println("The luxury totalCabins is: " + luxury17.totalCabins);
        System.out.println("The luxury availableCabins is: " + luxury17.availableCabins);
        System.out.println("The luxury isRoundTrip is: " + luxury17.isRoundTrip);
        System.out.println("The luxury dock is: " + luxury17.dock);
        System.out.println("The luxury terminal is: " + luxury17.terminal);
    }
}