public class Event001Runner 
{
	public static void main(String args[])
	{
        new Event001Runner();

        Event001 concert1 = new Event001();
        concert1.eventID = "EVT001";
        concert1.eventName = "Rock Concert";
        concert1.eventType = "Music";
        concert1.organizer = "Live Nation";
        concert1.location = "Madison Square Garden";
        concert1.date = "2024-10-20";
        concert1.time = "19:00";
        concert1.durationMinutes = 180;
        concert1.totalTickets = 20000;
        concert1.availableTickets = 5000;
        concert1.ticketPrice = 150.00;
        concert1.isIndoor = true;
        concert1.contactNumber = "+1 212-555-7890";
        concert1.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert1.eventID);
        System.out.println("The concert eventName is: " + concert1.eventName);
        System.out.println("The concert eventType is: " + concert1.eventType);
        System.out.println("The concert organizer is: " + concert1.organizer);
        System.out.println("The concert location is: " + concert1.location);
        System.out.println("The concert date is: " + concert1.date);
        System.out.println("The concert time is: " + concert1.time);
        System.out.println("The concert durationMinutes is: " + concert1.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert1.totalTickets);
        System.out.println("The concert availableTickets is: " + concert1.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert1.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert1.isIndoor);
        System.out.println("The concert contactNumber is: " + concert1.contactNumber);
        System.out.println("The concert website is: " + concert1.website);
		
		Event001 concert2 = new Event001();
        concert2.eventID = "EVT001";
        concert2.eventName = "Rock Concert";
        concert2.eventType = "Music";
        concert2.organizer = "Live Nation";
        concert2.location = "Madison Square Garden";
        concert2.date = "2024-10-20";
        concert2.time = "19:00";
        concert2.durationMinutes = 180;
        concert2.totalTickets = 20000;
        concert2.availableTickets = 5000;
        concert2.ticketPrice = 150.00;
        concert2.isIndoor = true;
        concert2.contactNumber = "+1 212-555-7890";
        concert2.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert2.eventID);
        System.out.println("The concert eventName is: " + concert2.eventName);
        System.out.println("The concert eventType is: " + concert2.eventType);
        System.out.println("The concert organizer is: " + concert2.organizer);
        System.out.println("The concert location is: " + concert2.location);
        System.out.println("The concert date is: " + concert2.date);
        System.out.println("The concert time is: " + concert2.time);
        System.out.println("The concert durationMinutes is: " + concert2.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert2.totalTickets);
        System.out.println("The concert availableTickets is: " + concert2.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert2.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert2.isIndoor);
        System.out.println("The concert contactNumber is: " + concert2.contactNumber);
        System.out.println("The concert website is: " + concert2.website);
		
		Event001 concert3 = new Event001();
        concert3.eventID = "EVT001";
        concert3.eventName = "Rock Concert";
        concert3.eventType = "Music";
        concert3.organizer = "Live Nation";
        concert3.location = "Madison Square Garden";
        concert3.date = "2024-10-20";
        concert3.time = "19:00";
        concert3.durationMinutes = 180;
        concert3.totalTickets = 20000;
        concert3.availableTickets = 5000;
        concert3.ticketPrice = 150.00;
        concert3.isIndoor = true;
        concert3.contactNumber = "+1 212-555-7890";
        concert3.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert3.eventID);
        System.out.println("The concert eventName is: " + concert3.eventName);
        System.out.println("The concert eventType is: " + concert3.eventType);
        System.out.println("The concert organizer is: " + concert3.organizer);
        System.out.println("The concert location is: " + concert3.location);
        System.out.println("The concert date is: " + concert3.date);
        System.out.println("The concert time is: " + concert3.time);
        System.out.println("The concert durationMinutes is: " + concert3.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert3.totalTickets);
        System.out.println("The concert availableTickets is: " + concert3.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert3.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert3.isIndoor);
        System.out.println("The concert contactNumber is: " + concert3.contactNumber);
        System.out.println("The concert website is: " + concert3.website);
		
		Event001 concert4 = new Event001();
        concert4.eventID = "EVT001";
        concert4.eventName = "Rock Concert";
        concert4.eventType = "Music";
        concert4.organizer = "Live Nation";
        concert4.location = "Madison Square Garden";
        concert4.date = "2024-10-20";
        concert4.time = "19:00";
        concert4.durationMinutes = 180;
        concert4.totalTickets = 20000;
        concert4.availableTickets = 5000;
        concert4.ticketPrice = 150.00;
        concert4.isIndoor = true;
        concert4.contactNumber = "+1 212-555-7890";
        concert4.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert4.eventID);
        System.out.println("The concert eventName is: " + concert4.eventName);
        System.out.println("The concert eventType is: " + concert4.eventType);
        System.out.println("The concert organizer is: " + concert4.organizer);
        System.out.println("The concert location is: " + concert4.location);
        System.out.println("The concert date is: " + concert4.date);
        System.out.println("The concert time is: " + concert4.time);
        System.out.println("The concert durationMinutes is: " + concert4.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert4.totalTickets);
        System.out.println("The concert availableTickets is: " + concert4.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert4.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert4.isIndoor);
        System.out.println("The concert contactNumber is: " + concert4.contactNumber);
        System.out.println("The concert website is: " + concert4.website);
		
		Event001 concert5 = new Event001();
        concert5.eventID = "EVT001";
        concert5.eventName = "Rock Concert";
        concert5.eventType = "Music";
        concert5.organizer = "Live Nation";
        concert5.location = "Madison Square Garden";
        concert5.date = "2024-10-20";
        concert5.time = "19:00";
        concert5.durationMinutes = 180;
        concert5.totalTickets = 20000;
        concert5.availableTickets = 5000;
        concert5.ticketPrice = 150.00;
        concert5.isIndoor = true;
        concert5.contactNumber = "+1 212-555-7890";
        concert5.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert5.eventID);
        System.out.println("The concert eventName is: " + concert5.eventName);
        System.out.println("The concert eventType is: " + concert5.eventType);
        System.out.println("The concert organizer is: " + concert5.organizer);
        System.out.println("The concert location is: " + concert5.location);
        System.out.println("The concert date is: " + concert5.date);
        System.out.println("The concert time is: " + concert5.time);
        System.out.println("The concert durationMinutes is: " + concert5.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert5.totalTickets);
        System.out.println("The concert availableTickets is: " + concert5.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert5.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert5.isIndoor);
        System.out.println("The concert contactNumber is: " + concert5.contactNumber);
        System.out.println("The concert website is: " + concert5.website);
		
		Event001 concert6 = new Event001();
        concert6.eventID = "EVT001";
        concert6.eventName = "Rock Concert";
        concert6.eventType = "Music";
        concert6.organizer = "Live Nation";
        concert6.location = "Madison Square Garden";
        concert6.date = "2024-10-20";
        concert6.time = "19:00";
        concert6.durationMinutes = 180;
        concert6.totalTickets = 20000;
        concert6.availableTickets = 5000;
        concert6.ticketPrice = 150.00;
        concert6.isIndoor = true;
        concert6.contactNumber = "+1 212-555-7890";
        concert6.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert6.eventID);
        System.out.println("The concert eventName is: " + concert6.eventName);
        System.out.println("The concert eventType is: " + concert6.eventType);
        System.out.println("The concert organizer is: " + concert6.organizer);
        System.out.println("The concert location is: " + concert6.location);
        System.out.println("The concert date is: " + concert6.date);
        System.out.println("The concert time is: " + concert6.time);
        System.out.println("The concert durationMinutes is: " + concert6.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert6.totalTickets);
        System.out.println("The concert availableTickets is: " + concert6.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert6.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert6.isIndoor);
        System.out.println("The concert contactNumber is: " + concert6.contactNumber);
        System.out.println("The concert website is: " + concert6.website);
		
		Event001 concert7 = new Event001();
        concert7.eventID = "EVT001";
        concert7.eventName = "Rock Concert";
        concert7.eventType = "Music";
        concert7.organizer = "Live Nation";
        concert7.location = "Madison Square Garden";
        concert7.date = "2024-10-20";
        concert7.time = "19:00";
        concert7.durationMinutes = 180;
        concert7.totalTickets = 20000;
        concert7.availableTickets = 5000;
        concert7.ticketPrice = 150.00;
        concert7.isIndoor = true;
        concert7.contactNumber = "+1 212-555-7890";
        concert7.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert7.eventID);
        System.out.println("The concert eventName is: " + concert7.eventName);
        System.out.println("The concert eventType is: " + concert7.eventType);
        System.out.println("The concert organizer is: " + concert7.organizer);
        System.out.println("The concert location is: " + concert7.location);
        System.out.println("The concert date is: " + concert7.date);
        System.out.println("The concert time is: " + concert7.time);
        System.out.println("The concert durationMinutes is: " + concert7.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert7.totalTickets);
        System.out.println("The concert availableTickets is: " + concert7.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert7.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert7.isIndoor);
        System.out.println("The concert contactNumber is: " + concert7.contactNumber);
        System.out.println("The concert website is: " + concert7.website);
		
		Event001 concert8 = new Event001();
        concert8.eventID = "EVT001";
        concert8.eventName = "Rock Concert";
        concert8.eventType = "Music";
        concert8.organizer = "Live Nation";
        concert8.location = "Madison Square Garden";
        concert8.date = "2024-10-20";
        concert8.time = "19:00";
        concert8.durationMinutes = 180;
        concert8.totalTickets = 20000;
        concert8.availableTickets = 5000;
        concert8.ticketPrice = 150.00;
        concert8.isIndoor = true;
        concert8.contactNumber = "+1 212-555-7890";
        concert8.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert8.eventID);
        System.out.println("The concert eventName is: " + concert8.eventName);
        System.out.println("The concert eventType is: " + concert8.eventType);
        System.out.println("The concert organizer is: " + concert8.organizer);
        System.out.println("The concert location is: " + concert8.location);
        System.out.println("The concert date is: " + concert8.date);
        System.out.println("The concert time is: " + concert8.time);
        System.out.println("The concert durationMinutes is: " + concert8.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert8.totalTickets);
        System.out.println("The concert availableTickets is: " + concert8.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert8.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert8.isIndoor);
        System.out.println("The concert contactNumber is: " + concert8.contactNumber);
        System.out.println("The concert website is: " + concert8.website);
		
		Event001 concert9 = new Event001();
        concert9.eventID = "EVT001";
        concert9.eventName = "Rock Concert";
        concert9.eventType = "Music";
        concert9.organizer = "Live Nation";
        concert9.location = "Madison Square Garden";
        concert9.date = "2024-10-20";
        concert9.time = "19:00";
        concert9.durationMinutes = 180;
        concert9.totalTickets = 20000;
        concert9.availableTickets = 5000;
        concert9.ticketPrice = 150.00;
        concert9.isIndoor = true;
        concert9.contactNumber = "+1 212-555-7890";
        concert9.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert9.eventID);
        System.out.println("The concert eventName is: " + concert9.eventName);
        System.out.println("The concert eventType is: " + concert9.eventType);
        System.out.println("The concert organizer is: " + concert9.organizer);
        System.out.println("The concert location is: " + concert9.location);
        System.out.println("The concert date is: " + concert9.date);
        System.out.println("The concert time is: " + concert9.time);
        System.out.println("The concert durationMinutes is: " + concert9.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert9.totalTickets);
        System.out.println("The concert availableTickets is: " + concert9.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert9.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert9.isIndoor);
        System.out.println("The concert contactNumber is: " + concert9.contactNumber);
        System.out.println("The concert website is: " + concert9.website);
		
		Event001 concert10 = new Event001();
        concert10.eventID = "EVT001";
        concert10.eventName = "Rock Concert";
        concert10.eventType = "Music";
        concert10.organizer = "Live Nation";
        concert10.location = "Madison Square Garden";
        concert10.date = "2024-10-20";
        concert10.time = "19:00";
        concert10.durationMinutes = 180;
        concert10.totalTickets = 20000;
        concert10.availableTickets = 5000;
        concert10.ticketPrice = 150.00;
        concert10.isIndoor = true;
        concert5.contactNumber = "+1 212-555-7890";
        concert5.website = "www.livenation.com";
        System.out.println("The concert eventID is: " + concert10.eventID);
        System.out.println("The concert eventName is: " + concert10.eventName);
        System.out.println("The concert eventType is: " + concert10.eventType);
        System.out.println("The concert organizer is: " + concert10.organizer);
        System.out.println("The concert location is: " + concert10.location);
        System.out.println("The concert date is: " + concert10.date);
        System.out.println("The concert time is: " + concert10.time);
        System.out.println("The concert durationMinutes is: " + concert10.durationMinutes);
        System.out.println("The concert totalTickets is: " + concert10.totalTickets);
        System.out.println("The concert availableTickets is: " + concert10.availableTickets);
        System.out.println("The concert ticketPrice is: " + concert10.ticketPrice);
        System.out.println("The concert isIndoor is: " + concert10.isIndoor);
        System.out.println("The concert contactNumber is: " + concert10.contactNumber);
        System.out.println("The concert website is: " + concert10.website);
    }
}