public class FlightRunner 
{
    public static void main(String args[]) 
	{
        new FlightRunner();

        Flight aero1 = new Flight();
        aero1.flightNumber = "AER2322";
        aero1.airline = "IndiGo";
        aero1.departureCity = "Bangaluru";
        aero1.arrivalCity = "Mumbai";
        aero1.departureTime = "07:00";
        aero1.arrivalTime = "10:00";
        aero1.durationMinutes = 180;
        aero1.ticketterminal = "N/A";
        aero1.aircraftType = "Airbus A318";
        aero1.totalSeats = 120;
        aero1.availableSeats = 80;
        aero1.isNonStop = false;
        aero1.gate = "GATE022";
        aero1.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero1.flightNumber);
        System.out.println("The aero airline is: " + aero1.airline);
        System.out.println("The aero departureCity is: " + aero1.departureCity);
        System.out.println("The aero publication year is: " + aero1.arrivalCity);
        System.out.println("The aero departureTime is: " + aero1.departureTime);
        System.out.println("The aero is available: " + aero1.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero1.durationMinutes);
        System.out.println("The aero due date is: " + aero1.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero1.aircraftType);
        System.out.println("The aero totalSeats is: " + aero1.totalSeats);
        System.out.println("The aero availableSeats is: " + aero1.availableSeats);
        System.out.println("The aero is digital: " + aero1.isNonStop);
        System.out.println("The aero gate is: " + aero1.gate);
        System.out.println("The aero terminal is: " + aero1.terminal);
		
		Flight aero2 = new Flight();
        aero2.flightNumber = "AER2322";
        aero2.airline = "IndiGo";
        aero2.departureCity = "Bangaluru";
        aero2.arrivalCity = "Mumbai";
        aero2.departureTime = "07:00";
        aero2.arrivalTime = "10:00";
        aero2.durationMinutes = 180;
        aero2.ticketterminal = "N/A";
        aero2.aircraftType = "Airbus A318";
        aero2.totalSeats = 120;
        aero2.availableSeats = 80;
        aero2.isNonStop = false;
        aero2.gate = "GATE022";
        aero2.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero2.flightNumber);
        System.out.println("The aero airline is: " + aero2.airline);
        System.out.println("The aero departureCity is: " + aero2.departureCity);
        System.out.println("The aero publication year is: " + aero2.arrivalCity);
        System.out.println("The aero departureTime is: " + aero2.departureTime);
        System.out.println("The aero is available: " + aero2.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero2.durationMinutes);
        System.out.println("The aero due date is: " + aero2.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero2.aircraftType);
        System.out.println("The aero totalSeats is: " + aero2.totalSeats);
        System.out.println("The aero availableSeats is: " + aero2.availableSeats);
        System.out.println("The aero is digital: " + aero2.isNonStop);
        System.out.println("The aero gate is: " + aero2.gate);
        System.out.println("The aero terminal is: " + aero2.terminal);
		
		Flight aero3 = new Flight();
        aero3.flightNumber = "AER2322";
        aero3.airline = "IndiGo";
        aero3.departureCity = "Bangaluru";
        aero3.arrivalCity = "Mumbai";
        aero3.departureTime = "07:00";
        aero3.arrivalTime = "10:00";
        aero3.durationMinutes = 180;
        aero3.ticketterminal = "N/A";
        aero3.aircraftType = "Airbus A318";
        aero3.totalSeats = 120;
        aero3.availableSeats = 80;
        aero3.isNonStop = false;
        aero3.gate = "GATE022";
        aero3.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero3.flightNumber);
        System.out.println("The aero airline is: " + aero3.airline);
        System.out.println("The aero departureCity is: " + aero3.departureCity);
        System.out.println("The aero publication year is: " + aero3.arrivalCity);
        System.out.println("The aero departureTime is: " + aero3.departureTime);
        System.out.println("The aero is available: " + aero3.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero3.durationMinutes);
        System.out.println("The aero due date is: " + aero3.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero3.aircraftType);
        System.out.println("The aero totalSeats is: " + aero3.totalSeats);
        System.out.println("The aero availableSeats is: " + aero3.availableSeats);
        System.out.println("The aero is digital: " + aero3.isNonStop);
        System.out.println("The aero gate is: " + aero3.gate);
        System.out.println("The aero terminal is: " + aero3.terminal);
		
		Flight aero4 = new Flight();
        aero4.flightNumber = "AER2322";
        aero4.airline = "IndiGo";
        aero4.departureCity = "Bangaluru";
        aero4.arrivalCity = "Mumbai";
        aero4.departureTime = "07:00";
        aero4.arrivalTime = "10:00";
        aero4.durationMinutes = 180;
        aero4.ticketterminal = "N/A";
        aero4.aircraftType = "Airbus A318";
        aero4.totalSeats = 120;
        aero4.availableSeats = 80;
        aero4.isNonStop = false;
        aero4.gate = "GATE022";
        aero4.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero4.flightNumber);
        System.out.println("The aero airline is: " + aero4.airline);
        System.out.println("The aero departureCity is: " + aero4.departureCity);
        System.out.println("The aero publication year is: " + aero4.arrivalCity);
        System.out.println("The aero departureTime is: " + aero4.departureTime);
        System.out.println("The aero is available: " + aero4.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero4.durationMinutes);
        System.out.println("The aero due date is: " + aero4.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero4.aircraftType);
        System.out.println("The aero totalSeats is: " + aero4.totalSeats);
        System.out.println("The aero availableSeats is: " + aero4.availableSeats);
        System.out.println("The aero is digital: " + aero4.isNonStop);
        System.out.println("The aero gate is: " + aero4.gate);
        System.out.println("The aero terminal is: " + aero4.terminal);
		
		Flight aero5 = new Flight();
        aero5.flightNumber = "AER2322";
        aero5.airline = "IndiGo";
        aero5.departureCity = "Bangaluru";
        aero5.arrivalCity = "Mumbai";
        aero5.departureTime = "07:00";
        aero5.arrivalTime = "10:00";
        aero5.durationMinutes = 180;
        aero5.ticketterminal = "N/A";
        aero5.aircraftType = "Airbus A318";
        aero5.totalSeats = 120;
        aero5.availableSeats = 80;
        aero5.isNonStop = false;
        aero5.gate = "GATE022";
        aero5.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero5.flightNumber);
        System.out.println("The aero airline is: " + aero5.airline);
        System.out.println("The aero departureCity is: " + aero5.departureCity);
        System.out.println("The aero publication year is: " + aero5.arrivalCity);
        System.out.println("The aero departureTime is: " + aero5.departureTime);
        System.out.println("The aero is available: " + aero5.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero5.durationMinutes);
        System.out.println("The aero due date is: " + aero5.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero5.aircraftType);
        System.out.println("The aero totalSeats is: " + aero5.totalSeats);
        System.out.println("The aero availableSeats is: " + aero5.availableSeats);
        System.out.println("The aero is digital: " + aero5.isNonStop);
        System.out.println("The aero gate is: " + aero5.gate);
        System.out.println("The aero terminal is: " + aero5.terminal);
		
		Flight aero6 = new Flight();
        aero6.flightNumber = "AER2322";
        aero6.airline = "IndiGo";
        aero6.departureCity = "Bangaluru";
        aero6.arrivalCity = "Mumbai";
        aero6.departureTime = "07:00";
        aero6.arrivalTime = "10:00";
        aero6.durationMinutes = 180;
        aero6.ticketterminal = "N/A";
        aero6.aircraftType = "Airbus A318";
        aero6.totalSeats = 120;
        aero6.availableSeats = 80;
        aero6.isNonStop = false;
        aero6.gate = "GATE022";
        aero6.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero6.flightNumber);
        System.out.println("The aero airline is: " + aero6.airline);
        System.out.println("The aero departureCity is: " + aero6.departureCity);
        System.out.println("The aero publication year is: " + aero6.arrivalCity);
        System.out.println("The aero departureTime is: " + aero6.departureTime);
        System.out.println("The aero is available: " + aero6.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero6.durationMinutes);
        System.out.println("The aero due date is: " + aero6.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero6.aircraftType);
        System.out.println("The aero totalSeats is: " + aero6.totalSeats);
        System.out.println("The aero availableSeats is: " + aero6.availableSeats);
        System.out.println("The aero is digital: " + aero6.isNonStop);
        System.out.println("The aero gate is: " + aero6.gate);
        System.out.println("The aero terminal is: " + aero6.terminal);
		
		Flight aero7 = new Flight();
        aero7.flightNumber = "AER2322";
        aero7.airline = "IndiGo";
        aero7.departureCity = "Bangaluru";
        aero7.arrivalCity = "Mumbai";
        aero7.departureTime = "07:00";
        aero7.arrivalTime = "10:00";
        aero7.durationMinutes = 180;
        aero7.ticketterminal = "N/A";
        aero7.aircraftType = "Airbus A318";
        aero7.totalSeats = 120;
        aero7.availableSeats = 80;
        aero7.isNonStop = false;
        aero7.gate = "GATE022";
        aero7.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero7.flightNumber);
        System.out.println("The aero airline is: " + aero7.airline);
        System.out.println("The aero departureCity is: " + aero7.departureCity);
        System.out.println("The aero publication year is: " + aero7.arrivalCity);
        System.out.println("The aero departureTime is: " + aero7.departureTime);
        System.out.println("The aero is available: " + aero7.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero7.durationMinutes);
        System.out.println("The aero due date is: " + aero7.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero7.aircraftType);
        System.out.println("The aero totalSeats is: " + aero7.totalSeats);
        System.out.println("The aero availableSeats is: " + aero7.availableSeats);
        System.out.println("The aero is digital: " + aero7.isNonStop);
        System.out.println("The aero gate is: " + aero7.gate);
        System.out.println("The aero terminal is: " + aero7.terminal);
		
		Flight aero8 = new Flight();
        aero8.flightNumber = "AER2322";
        aero8.airline = "IndiGo";
        aero8.departureCity = "Bangaluru";
        aero8.arrivalCity = "Mumbai";
        aero8.departureTime = "07:00";
        aero8.arrivalTime = "10:00";
        aero8.durationMinutes = 180;
        aero8.ticketterminal = "N/A";
        aero8.aircraftType = "Airbus A318";
        aero8.totalSeats = 120;
        aero8.availableSeats = 80;
        aero8.isNonStop = false;
        aero8.gate = "GATE022";
        aero8.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero8.flightNumber);
        System.out.println("The aero airline is: " + aero8.airline);
        System.out.println("The aero departureCity is: " + aero8.departureCity);
        System.out.println("The aero publication year is: " + aero8.arrivalCity);
        System.out.println("The aero departureTime is: " + aero8.departureTime);
        System.out.println("The aero is available: " + aero8.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero8.durationMinutes);
        System.out.println("The aero due date is: " + aero8.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero8.aircraftType);
        System.out.println("The aero totalSeats is: " + aero8.totalSeats);
        System.out.println("The aero availableSeats is: " + aero8.availableSeats);
        System.out.println("The aero is digital: " + aero8.isNonStop);
        System.out.println("The aero gate is: " + aero8.gate);
        System.out.println("The aero terminal is: " + aero8.terminal);
		
		Flight aero9 = new Flight();
        aero9.flightNumber = "AER2322";
        aero9.airline = "IndiGo";
        aero9.departureCity = "Bangaluru";
        aero9.arrivalCity = "Mumbai";
        aero9.departureTime = "07:00";
        aero9.arrivalTime = "10:00";
        aero9.durationMinutes = 180;
        aero9.ticketterminal = "N/A";
        aero9.aircraftType = "Airbus A318";
        aero9.totalSeats = 120;
        aero9.availableSeats = 80;
        aero9.isNonStop = false;
        aero9.gate = "GATE022";
        aero9.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero9.flightNumber);
        System.out.println("The aero airline is: " + aero9.airline);
        System.out.println("The aero departureCity is: " + aero9.departureCity);
        System.out.println("The aero publication year is: " + aero9.arrivalCity);
        System.out.println("The aero departureTime is: " + aero9.departureTime);
        System.out.println("The aero is available: " + aero9.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero9.durationMinutes);
        System.out.println("The aero due date is: " + aero9.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero9.aircraftType);
        System.out.println("The aero totalSeats is: " + aero9.totalSeats);
        System.out.println("The aero availableSeats is: " + aero9.availableSeats);
        System.out.println("The aero is digital: " + aero9.isNonStop);
        System.out.println("The aero gate is: " + aero9.gate);
        System.out.println("The aero terminal is: " + aero9.terminal);
		
		Flight aero10 = new Flight();
        aero10.flightNumber = "AER2322";
        aero10.airline = "IndiGo";
        aero10.departureCity = "Bangaluru";
        aero10.arrivalCity = "Mumbai";
        aero10.departureTime = "07:00";
        aero10.arrivalTime = "10:00";
        aero10.durationMinutes = 180;
        aero10.ticketterminal = "N/A";
        aero10.aircraftType = "Airbus A318";
        aero10.totalSeats = 120;
        aero10.availableSeats = 80;
        aero10.isNonStop = false;
        aero10.gate = "GATE022";
        aero10.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero10.flightNumber);
        System.out.println("The aero airline is: " + aero10.airline);
        System.out.println("The aero departureCity is: " + aero10.departureCity);
        System.out.println("The aero publication year is: " + aero10.arrivalCity);
        System.out.println("The aero departureTime is: " + aero10.departureTime);
        System.out.println("The aero is available: " + aero10.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero10.durationMinutes);
        System.out.println("The aero due date is: " + aero10.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero10.aircraftType);
        System.out.println("The aero totalSeats is: " + aero10.totalSeats);
        System.out.println("The aero availableSeats is: " + aero10.availableSeats);
        System.out.println("The aero is digital: " + aero10.isNonStop);
        System.out.println("The aero gate is: " + aero10.gate);
        System.out.println("The aero terminal is: " + aero10.terminal);
		
		Flight aero11 = new Flight();
        aero11.flightNumber = "AER2322";
        aero11.airline = "IndiGo";
        aero11.departureCity = "Bangaluru";
        aero11.arrivalCity = "Mumbai";
        aero11.departureTime = "07:00";
        aero11.arrivalTime = "10:00";
        aero11.durationMinutes = 180;
        aero11.ticketterminal = "N/A";
        aero11.aircraftType = "Airbus A318";
        aero11.totalSeats = 120;
        aero11.availableSeats = 80;
        aero11.isNonStop = false;
        aero11.gate = "GATE022";
        aero11.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero11.flightNumber);
        System.out.println("The aero airline is: " + aero11.airline);
        System.out.println("The aero departureCity is: " + aero11.departureCity);
        System.out.println("The aero publication year is: " + aero11.arrivalCity);
        System.out.println("The aero departureTime is: " + aero11.departureTime);
        System.out.println("The aero is available: " + aero11.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero11.durationMinutes);
        System.out.println("The aero due date is: " + aero11.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero11.aircraftType);
        System.out.println("The aero totalSeats is: " + aero11.totalSeats);
        System.out.println("The aero availableSeats is: " + aero11.availableSeats);
        System.out.println("The aero is digital: " + aero11.isNonStop);
        System.out.println("The aero gate is: " + aero11.gate);
        System.out.println("The aero terminal is: " + aero11.terminal);
		
		Flight aero12 = new Flight();
        aero12.flightNumber = "AER2322";
        aero12.airline = "IndiGo";
        aero12.departureCity = "Bangaluru";
        aero12.arrivalCity = "Mumbai";
        aero12.departureTime = "07:00";
        aero12.arrivalTime = "10:00";
        aero12.durationMinutes = 180;
        aero12.ticketterminal = "N/A";
        aero12.aircraftType = "Airbus A318";
        aero12.totalSeats = 120;
        aero12.availableSeats = 80;
        aero12.isNonStop = false;
        aero12.gate = "GATE022";
        aero12.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero12.flightNumber);
        System.out.println("The aero airline is: " + aero12.airline);
        System.out.println("The aero departureCity is: " + aero12.departureCity);
        System.out.println("The aero publication year is: " + aero12.arrivalCity);
        System.out.println("The aero departureTime is: " + aero12.departureTime);
        System.out.println("The aero is available: " + aero12.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero12.durationMinutes);
        System.out.println("The aero due date is: " + aero12.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero12.aircraftType);
        System.out.println("The aero totalSeats is: " + aero12.totalSeats);
        System.out.println("The aero availableSeats is: " + aero12.availableSeats);
        System.out.println("The aero is digital: " + aero12.isNonStop);
        System.out.println("The aero gate is: " + aero12.gate);
        System.out.println("The aero terminal is: " + aero12.terminal);
		
		Flight aero13 = new Flight();
        aero13.flightNumber = "AER2322";
        aero13.airline = "IndiGo";
        aero13.departureCity = "Bangaluru";
        aero13.arrivalCity = "Mumbai";
        aero13.departureTime = "07:00";
        aero13.arrivalTime = "10:00";
        aero13.durationMinutes = 180;
        aero13.ticketterminal = "N/A";
        aero13.aircraftType = "Airbus A318";
        aero13.totalSeats = 120;
        aero13.availableSeats = 80;
        aero13.isNonStop = false;
        aero13.gate = "GATE022";
        aero13.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero13.flightNumber);
        System.out.println("The aero airline is: " + aero13.airline);
        System.out.println("The aero departureCity is: " + aero13.departureCity);
        System.out.println("The aero publication year is: " + aero13.arrivalCity);
        System.out.println("The aero departureTime is: " + aero13.departureTime);
        System.out.println("The aero is available: " + aero13.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero13.durationMinutes);
        System.out.println("The aero due date is: " + aero13.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero13.aircraftType);
        System.out.println("The aero totalSeats is: " + aero13.totalSeats);
        System.out.println("The aero availableSeats is: " + aero13.availableSeats);
        System.out.println("The aero is digital: " + aero13.isNonStop);
        System.out.println("The aero gate is: " + aero13.gate);
        System.out.println("The aero terminal is: " + aero13.terminal);
		
		Flight aero14 = new Flight();
        aero14.flightNumber = "AER2322";
        aero14.airline = "IndiGo";
        aero14.departureCity = "Bangaluru";
        aero14.arrivalCity = "Mumbai";
        aero14.departureTime = "07:00";
        aero14.arrivalTime = "10:00";
        aero14.durationMinutes = 180;
        aero14.ticketterminal = "N/A";
        aero14.aircraftType = "Airbus A318";
        aero14.totalSeats = 120;
        aero14.availableSeats = 80;
        aero14.isNonStop = false;
        aero14.gate = "GATE022";
        aero14.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero14.flightNumber);
        System.out.println("The aero airline is: " + aero14.airline);
        System.out.println("The aero departureCity is: " + aero14.departureCity);
        System.out.println("The aero publication year is: " + aero14.arrivalCity);
        System.out.println("The aero departureTime is: " + aero14.departureTime);
        System.out.println("The aero is available: " + aero14.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero14.durationMinutes);
        System.out.println("The aero due date is: " + aero14.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero14.aircraftType);
        System.out.println("The aero totalSeats is: " + aero14.totalSeats);
        System.out.println("The aero availableSeats is: " + aero14.availableSeats);
        System.out.println("The aero is digital: " + aero14.isNonStop);
        System.out.println("The aero gate is: " + aero14.gate);
        System.out.println("The aero terminal is: " + aero14.terminal);
		
		Flight aero15 = new Flight();
        aero15.flightNumber = "AER2322";
        aero15.airline = "IndiGo";
        aero15.departureCity = "Bangaluru";
        aero15.arrivalCity = "Mumbai";
        aero15.departureTime = "07:00";
        aero15.arrivalTime = "10:00";
        aero15.durationMinutes = 180;
        aero15.ticketterminal = "N/A";
        aero15.aircraftType = "Airbus A318";
        aero15.totalSeats = 120;
        aero15.availableSeats = 80;
        aero15.isNonStop = false;
        aero15.gate = "GATE022";
        aero15.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero15.flightNumber);
        System.out.println("The aero airline is: " + aero15.airline);
        System.out.println("The aero departureCity is: " + aero15.departureCity);
        System.out.println("The aero publication year is: " + aero15.arrivalCity);
        System.out.println("The aero departureTime is: " + aero15.departureTime);
        System.out.println("The aero is available: " + aero15.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero15.durationMinutes);
        System.out.println("The aero due date is: " + aero15.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero15.aircraftType);
        System.out.println("The aero totalSeats is: " + aero15.totalSeats);
        System.out.println("The aero availableSeats is: " + aero15.availableSeats);
        System.out.println("The aero is digital: " + aero15.isNonStop);
        System.out.println("The aero gate is: " + aero15.gate);
        System.out.println("The aero terminal is: " + aero15.terminal);
		
		Flight aero16 = new Flight();
        aero16.flightNumber = "AER2322";
        aero16.airline = "IndiGo";
        aero16.departureCity = "Bangaluru";
        aero16.arrivalCity = "Mumbai";
        aero16.departureTime = "07:00";
        aero16.arrivalTime = "10:00";
        aero16.durationMinutes = 180;
        aero16.ticketterminal = "N/A";
        aero16.aircraftType = "Airbus A318";
        aero16.totalSeats = 120;
        aero16.availableSeats = 80;
        aero16.isNonStop = false;
        aero16.gate = "GATE022";
        aero16.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero16.flightNumber);
        System.out.println("The aero airline is: " + aero16.airline);
        System.out.println("The aero departureCity is: " + aero16.departureCity);
        System.out.println("The aero publication year is: " + aero16.arrivalCity);
        System.out.println("The aero departureTime is: " + aero16.departureTime);
        System.out.println("The aero is available: " + aero16.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero16.durationMinutes);
        System.out.println("The aero due date is: " + aero16.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero16.aircraftType);
        System.out.println("The aero totalSeats is: " + aero16.totalSeats);
        System.out.println("The aero availableSeats is: " + aero16.availableSeats);
        System.out.println("The aero is digital: " + aero16.isNonStop);
        System.out.println("The aero gate is: " + aero16.gate);
        System.out.println("The aero terminal is: " + aero16.terminal);
		
		Flight aero17 = new Flight();
        aero17.flightNumber = "AER2322";
        aero17.airline = "IndiGo";
        aero17.departureCity = "Bangaluru";
        aero17.arrivalCity = "Mumbai";
        aero17.departureTime = "07:00";
        aero17.arrivalTime = "10:00";
        aero17.durationMinutes = 180;
        aero17.ticketterminal = "N/A";
        aero17.aircraftType = "Airbus A318";
        aero17.totalSeats = 120;
        aero17.availableSeats = 80;
        aero17.isNonStop = false;
        aero17.gate = "GATE022";
        aero17.terminal = "T15";
        System.out.println("The aero flightNumber is: " + aero17.flightNumber);
        System.out.println("The aero airline is: " + aero17.airline);
        System.out.println("The aero departureCity is: " + aero17.departureCity);
        System.out.println("The aero publication year is: " + aero17.arrivalCity);
        System.out.println("The aero departureTime is: " + aero17.departureTime);
        System.out.println("The aero is available: " + aero17.arrivalTime);
        System.out.println("The aero durationMinutes is: " + aero17.durationMinutes);
        System.out.println("The aero due date is: " + aero17.ticketterminal);
        System.out.println("The aero aircraftType are: " + aero17.aircraftType);
        System.out.println("The aero totalSeats is: " + aero17.totalSeats);
        System.out.println("The aero availableSeats is: " + aero17.availableSeats);
        System.out.println("The aero is digital: " + aero17.isNonStop);
        System.out.println("The aero gate is: " + aero17.gate);
        System.out.println("The aero terminal is: " + aero17.terminal);
    }
}
