public class LaptopStoreRunner
{
    public static void main(String args[])
	{
        new LaptopStoreRunner();

        LaptopStore myLaptop = new LaptopStore();
        myLaptop.serialNumber = "ABC123456789";
        myLaptop.brand = "Dell";
        myLaptop.model = "XPS 15";
        myLaptop.screenSize = 15.6;
        myLaptop.processor = "Intel Core i9";
        myLaptop.ramGB = 32;
        myLaptop.storageGB = 1000;
        myLaptop.operatingSystem = "Windows 11";
        myLaptop.isTouchscreen = true;
        myLaptop.hasBacklitKeyboard = true;
        myLaptop.price = 2499.99;
        myLaptop.color = "Silver";
		myLaptop.weight = 2;
        System.out.println("Serial Number: " + myLaptop.serialNumber);
        System.out.println("Brand: " + myLaptop.brand);
        System.out.println("Model: " + myLaptop.model);
        System.out.println("Screen Size: " + myLaptop.screenSize + " inches");
        System.out.println("Processor: " + myLaptop.processor);
        System.out.println("RAM: " + myLaptop.ramGB + " GB");
        System.out.println("Storage: " + myLaptop.storageGB + " GB");
        System.out.println("Operating System: " + myLaptop.operatingSystem);
        System.out.println("Touchscreen: " + myLaptop.isTouchscreen);
        System.out.println("Backlit Keyboard: " + myLaptop.hasBacklitKeyboard);
        System.out.println("Price: $" + myLaptop.price);
        System.out.println("Color: " + myLaptop.color);
		System.out.println("Weight: " + myLaptop.weight + "Kg");
		
		LaptopStore myLaptop2 = new LaptopStore();
        myLaptop2.serialNumber = "ABC123456789";
        myLaptop2.brand = "Dell";
        myLaptop2.model = "XPS 15";
        myLaptop2.screenSize = 15.6;
        myLaptop2.processor = "Intel Core i9";
        myLaptop2.ramGB = 32;
        myLaptop2.storageGB = 1000;
        myLaptop2.operatingSystem = "Windows 11";
        myLaptop2.isTouchscreen = true;
        myLaptop2.hasBacklitKeyboard = true;
        myLaptop2.price = 2499.99;
        myLaptop2.color = "Silver";
		myLaptop2.weight = 2;
        System.out.println("Serial Number: " + myLaptop2.serialNumber);
        System.out.println("Brand: " + myLaptop2.brand);
        System.out.println("Model: " + myLaptop2.model);
        System.out.println("Screen Size: " + myLaptop2.screenSize + " inches");
        System.out.println("Processor: " + myLaptop2.processor);
        System.out.println("RAM: " + myLaptop2.ramGB + " GB");
        System.out.println("Storage: " + myLaptop2.storageGB + " GB");
        System.out.println("Operating System: " + myLaptop2.operatingSystem);
        System.out.println("Touchscreen: " + myLaptop2.isTouchscreen);
        System.out.println("Backlit Keyboard: " + myLaptop2.hasBacklitKeyboard);
        System.out.println("Price: $" + myLaptop2.price);
        System.out.println("Color: " + myLaptop2.color);
		System.out.println("Weight: " + myLaptop2.weight + "Kg");
		
		LaptopStore myLaptop3 = new LaptopStore();
        myLaptop3.serialNumber = "ABC123456789";
        myLaptop3.brand = "Dell";
        myLaptop3.model = "XPS 15";
        myLaptop3.screenSize = 15.6;
        myLaptop3.processor = "Intel Core i9";
        myLaptop3.ramGB = 32;
        myLaptop3.storageGB = 1000;
        myLaptop3.operatingSystem = "Windows 11";
        myLaptop3.isTouchscreen = true;
        myLaptop3.hasBacklitKeyboard = true;
        myLaptop3.price = 2499.99;
        myLaptop3.color = "Silver";
		myLaptop3.weight = 2;
        System.out.println("Serial Number: " + myLaptop3.serialNumber);
        System.out.println("Brand: " + myLaptop3.brand);
        System.out.println("Model: " + myLaptop3.model);
        System.out.println("Screen Size: " + myLaptop3.screenSize + " inches");
        System.out.println("Processor: " + myLaptop3.processor);
        System.out.println("RAM: " + myLaptop3.ramGB + " GB");
        System.out.println("Storage: " + myLaptop3.storageGB + " GB");
        System.out.println("Operating System: " + myLaptop3.operatingSystem);
        System.out.println("Touchscreen: " + myLaptop3.isTouchscreen);
        System.out.println("Backlit Keyboard: " + myLaptop3.hasBacklitKeyboard);
        System.out.println("Price: $" + myLaptop3.price);
        System.out.println("Color: " + myLaptop3.color);
		System.out.println("Weight: " + myLaptop3.weight + "Kg");
		
		LaptopStore myLaptop4 = new LaptopStore();
        myLaptop4.serialNumber = "ABC123456789";
        myLaptop4.brand = "Dell";
        myLaptop4.model = "XPS 15";
        myLaptop4.screenSize = 15.6;
        myLaptop4.processor = "Intel Core i9";
        myLaptop4.ramGB = 32;
        myLaptop4.storageGB = 1000;
        myLaptop4.operatingSystem = "Windows 11";
        myLaptop4.isTouchscreen = true;
        myLaptop4.hasBacklitKeyboard = true;
        myLaptop4.price = 2499.99;
        myLaptop4.color = "Silver";
		myLaptop4.weight = 2;
        System.out.println("Serial Number: " + myLaptop4.serialNumber);
        System.out.println("Brand: " + myLaptop4.brand);
        System.out.println("Model: " + myLaptop4.model);
        System.out.println("Screen Size: " + myLaptop4.screenSize + " inches");
        System.out.println("Processor: " + myLaptop4.processor);
        System.out.println("RAM: " + myLaptop4.ramGB + " GB");
        System.out.println("Storage: " + myLaptop4.storageGB + " GB");
        System.out.println("Operating System: " + myLaptop4.operatingSystem);
        System.out.println("Touchscreen: " + myLaptop4.isTouchscreen);
        System.out.println("Backlit Keyboard: " + myLaptop4.hasBacklitKeyboard);
        System.out.println("Price: $" + myLaptop4.price);
        System.out.println("Color: " + myLaptop4.color);
		System.out.println("Weight: " + myLaptop4.weight + "Kg");
		
		LaptopStore myLaptop5 = new LaptopStore();
        myLaptop5.serialNumber = "ABC123456789";
        myLaptop5.brand = "Dell";
        myLaptop5.model = "XPS 15";
        myLaptop5.screenSize = 15.6;
        myLaptop5.processor = "Intel Core i9";
        myLaptop5.ramGB = 32;
        myLaptop5.storageGB = 1000;
        myLaptop5.operatingSystem = "Windows 11";
        myLaptop5.isTouchscreen = true;
        myLaptop5.hasBacklitKeyboard = true;
        myLaptop5.price = 2499.99;
        myLaptop5.color = "Silver";
		myLaptop5.weight = 2;
        System.out.println("Serial Number: " + myLaptop5.serialNumber);
        System.out.println("Brand: " + myLaptop5.brand);
        System.out.println("Model: " + myLaptop5.model);
        System.out.println("Screen Size: " + myLaptop5.screenSize + " inches");
        System.out.println("Processor: " + myLaptop5.processor);
        System.out.println("RAM: " + myLaptop5.ramGB + " GB");
        System.out.println("Storage: " + myLaptop5.storageGB + " GB");
        System.out.println("Operating System: " + myLaptop5.operatingSystem);
        System.out.println("Touchscreen: " + myLaptop5.isTouchscreen);
        System.out.println("Backlit Keyboard: " + myLaptop5.hasBacklitKeyboard);
        System.out.println("Price: $" + myLaptop5.price);
        System.out.println("Color: " + myLaptop5.color);
		System.out.println("Weight: " + myLaptop5.weight + "Kg");
    }
}
