public class LibraryBookRunner 
{
    public static void main(String args[]) 
	{
        new LibraryBookRunner();

        LibraryBook book1 = new LibraryBook();
        book1.title = "The Great Gatsby";
        book1.author = "F. Scott Fitzgerald";
        book1.isbn = "9780743273565";
        book1.publicationYear = 1925;
        book1.genre = "Novel";
        book1.isAvailable = true;
        book1.borrower = "None";
        book1.dueDate = "N/A";
        book1.pages = 218;
        book1.publisher = "Charles Scribner's Sons";
        book1.language = "English";
        book1.isDigital = false;
        book1.format = "Hardcover";
        book1.price = 10.99;
        System.out.println("The Book title is: " + book1.title);
        System.out.println("The Book author is: " + book1.author);
        System.out.println("The Book ISBN is: " + book1.isbn);
        System.out.println("The Book publication year is: " + book1.publicationYear);
        System.out.println("The Book genre is: " + book1.genre);
        System.out.println("The Book is available: " + book1.isAvailable);
        System.out.println("The Book borrower is: " + book1.borrower);
        System.out.println("The Book due date is: " + book1.dueDate);
        System.out.println("The Book pages are: " + book1.pages);
        System.out.println("The Book publisher is: " + book1.publisher);
        System.out.println("The Book language is: " + book1.language);
        System.out.println("The Book is digital: " + book1.isDigital);
        System.out.println("The Book format is: " + book1.format);
        System.out.println("The Book price is: " + book1.price);
		
		LibraryBook book2 = new LibraryBook();
        book2.title = "The Great Gatsby";
        book2.author = "F. Scott Fitzgerald";
        book2.isbn = "9780743273565";
        book2.publicationYear = 1925;
        book2.genre = "Novel";
        book2.isAvailable = true;
        book2.borrower = "None";
        book2.dueDate = "N/A";
        book2.pages = 218;
        book2.publisher = "Charles Scribner's Sons";
        book2.language = "English";
        book2.isDigital = false;
        book2.format = "Hardcover";
        book2.price = 10.99;
        System.out.println("The Book title is: " + book2.title);
        System.out.println("The Book author is: " + book2.author);
        System.out.println("The Book ISBN is: " + book2.isbn);
        System.out.println("The Book publication year is: " + book2.publicationYear);
        System.out.println("The Book genre is: " + book2.genre);
        System.out.println("The Book is available: " + book2.isAvailable);
        System.out.println("The Book borrower is: " + book2.borrower);
        System.out.println("The Book due date is: " + book2.dueDate);
        System.out.println("The Book pages are: " + book2.pages);
        System.out.println("The Book publisher is: " + book2.publisher);
        System.out.println("The Book language is: " + book2.language);
        System.out.println("The Book is digital: " + book2.isDigital);
        System.out.println("The Book format is: " + book2.format);
        System.out.println("The Book price is: " + book2.price);
		
		LibraryBook book3 = new LibraryBook();
        book3.title = "The Great Gatsby";
        book3.author = "F. Scott Fitzgerald";
        book3.isbn = "9780743273565";
        book3.publicationYear = 1925;
        book3.genre = "Novel";
        book3.isAvailable = true;
        book3.borrower = "None";
        book3.dueDate = "N/A";
        book3.pages = 218;
        book3.publisher = "Charles Scribner's Sons";
        book3.language = "English";
        book3.isDigital = false;
        book3.format = "Hardcover";
        book3.price = 10.99;
        System.out.println("The Book title is: " + book3.title);
        System.out.println("The Book author is: " + book3.author);
        System.out.println("The Book ISBN is: " + book3.isbn);
        System.out.println("The Book publication year is: " + book3.publicationYear);
        System.out.println("The Book genre is: " + book3.genre);
        System.out.println("The Book is available: " + book3.isAvailable);
        System.out.println("The Book borrower is: " + book3.borrower);
        System.out.println("The Book due date is: " + book3.dueDate);
        System.out.println("The Book pages are: " + book3.pages);
        System.out.println("The Book publisher is: " + book3.publisher);
        System.out.println("The Book language is: " + book3.language);
        System.out.println("The Book is digital: " + book3.isDigital);
        System.out.println("The Book format is: " + book3.format);
        System.out.println("The Book price is: " + book3.price);
		
		LibraryBook book4 = new LibraryBook();
        book4.title = "The Great Gatsby";
        book4.author = "F. Scott Fitzgerald";
        book4.isbn = "9780743273565";
        book4.publicationYear = 1925;
        book4.genre = "Novel";
        book4.isAvailable = true;
        book4.borrower = "None";
        book4.dueDate = "N/A";
        book4.pages = 218;
        book4.publisher = "Charles Scribner's Sons";
        book4.language = "English";
        book4.isDigital = false;
        book4.format = "Hardcover";
        book4.price = 10.99;
        System.out.println("The Book title is: " + book4.title);
        System.out.println("The Book author is: " + book4.author);
        System.out.println("The Book ISBN is: " + book4.isbn);
        System.out.println("The Book publication year is: " + book4.publicationYear);
        System.out.println("The Book genre is: " + book4.genre);
        System.out.println("The Book is available: " + book4.isAvailable);
        System.out.println("The Book borrower is: " + book4.borrower);
        System.out.println("The Book due date is: " + book4.dueDate);
        System.out.println("The Book pages are: " + book4.pages);
        System.out.println("The Book publisher is: " + book4.publisher);
        System.out.println("The Book language is: " + book4.language);
        System.out.println("The Book is digital: " + book4.isDigital);
        System.out.println("The Book format is: " + book4.format);
        System.out.println("The Book price is: " + book4.price);
		
		LibraryBook book5 = new LibraryBook();
        book5.title = "The Great Gatsby";
        book5.author = "F. Scott Fitzgerald";
        book5.isbn = "9780743273565";
        book5.publicationYear = 1925;
        book5.genre = "Novel";
        book5.isAvailable = true;
        book5.borrower = "None";
        book5.dueDate = "N/A";
        book5.pages = 218;
        book5.publisher = "Charles Scribner's Sons";
        book5.language = "English";
        book5.isDigital = false;
        book5.format = "Hardcover";
        book5.price = 10.99;
        System.out.println("The Book title is: " + book5.title);
        System.out.println("The Book author is: " + book5.author);
        System.out.println("The Book ISBN is: " + book5.isbn);
        System.out.println("The Book publication year is: " + book5.publicationYear);
        System.out.println("The Book genre is: " + book5.genre);
        System.out.println("The Book is available: " + book5.isAvailable);
        System.out.println("The Book borrower is: " + book5.borrower);
        System.out.println("The Book due date is: " + book5.dueDate);
        System.out.println("The Book pages are: " + book5.pages);
        System.out.println("The Book publisher is: " + book5.publisher);
        System.out.println("The Book language is: " + book5.language);
        System.out.println("The Book is digital: " + book5.isDigital);
        System.out.println("The Book format is: " + book5.format);
        System.out.println("The Book price is: " + book5.price);
		
		LibraryBook book6 = new LibraryBook();
        book6.title = "The Great Gatsby";
        book6.author = "F. Scott Fitzgerald";
        book6.isbn = "9780743273565";
        book6.publicationYear = 1925;
        book6.genre = "Novel";
        book6.isAvailable = true;
        book6.borrower = "None";
        book6.dueDate = "N/A";
        book6.pages = 218;
        book6.publisher = "Charles Scribner's Sons";
        book6.language = "English";
        book6.isDigital = false;
        book6.format = "Hardcover";
        book6.price = 10.99;
        System.out.println("The Book title is: " + book6.title);
        System.out.println("The Book author is: " + book6.author);
        System.out.println("The Book ISBN is: " + book6.isbn);
        System.out.println("The Book publication year is: " + book6.publicationYear);
        System.out.println("The Book genre is: " + book6.genre);
        System.out.println("The Book is available: " + book6.isAvailable);
        System.out.println("The Book borrower is: " + book6.borrower);
        System.out.println("The Book due date is: " + book6.dueDate);
        System.out.println("The Book pages are: " + book6.pages);
        System.out.println("The Book publisher is: " + book6.publisher);
        System.out.println("The Book language is: " + book6.language);
        System.out.println("The Book is digital: " + book6.isDigital);
        System.out.println("The Book format is: " + book6.format);
        System.out.println("The Book price is: " + book6.price);
		
		LibraryBook book7 = new LibraryBook();
        book7.title = "The Great Gatsby";
        book7.author = "F. Scott Fitzgerald";
        book7.isbn = "9780743273565";
        book7.publicationYear = 1925;
        book7.genre = "Novel";
        book7.isAvailable = true;
        book7.borrower = "None";
        book7.dueDate = "N/A";
        book7.pages = 218;
        book7.publisher = "Charles Scribner's Sons";
        book7.language = "English";
        book7.isDigital = false;
        book7.format = "Hardcover";
        book7.price = 10.99;
        System.out.println("The Book title is: " + book7.title);
        System.out.println("The Book author is: " + book7.author);
        System.out.println("The Book ISBN is: " + book7.isbn);
        System.out.println("The Book publication year is: " + book7.publicationYear);
        System.out.println("The Book genre is: " + book7.genre);
        System.out.println("The Book is available: " + book7.isAvailable);
        System.out.println("The Book borrower is: " + book7.borrower);
        System.out.println("The Book due date is: " + book7.dueDate);
        System.out.println("The Book pages are: " + book7.pages);
        System.out.println("The Book publisher is: " + book7.publisher);
        System.out.println("The Book language is: " + book7.language);
        System.out.println("The Book is digital: " + book7.isDigital);
        System.out.println("The Book format is: " + book7.format);
        System.out.println("The Book price is: " + book7.price);
		
		LibraryBook book8 = new LibraryBook();
        book8.title = "The Great Gatsby";
        book8.author = "F. Scott Fitzgerald";
        book8.isbn = "9780743273565";
        book8.publicationYear = 1925;
        book8.genre = "Novel";
        book8.isAvailable = true;
        book8.borrower = "None";
        book8.dueDate = "N/A";
        book8.pages = 218;
        book8.publisher = "Charles Scribner's Sons";
        book8.language = "English";
        book8.isDigital = false;
        book8.format = "Hardcover";
        book8.price = 10.99;
        System.out.println("The Book title is: " + book8.title);
        System.out.println("The Book author is: " + book8.author);
        System.out.println("The Book ISBN is: " + book8.isbn);
        System.out.println("The Book publication year is: " + book8.publicationYear);
        System.out.println("The Book genre is: " + book8.genre);
        System.out.println("The Book is available: " + book8.isAvailable);
        System.out.println("The Book borrower is: " + book8.borrower);
        System.out.println("The Book due date is: " + book8.dueDate);
        System.out.println("The Book pages are: " + book8.pages);
        System.out.println("The Book publisher is: " + book8.publisher);
        System.out.println("The Book language is: " + book8.language);
        System.out.println("The Book is digital: " + book8.isDigital);
        System.out.println("The Book format is: " + book8.format);
        System.out.println("The Book price is: " + book8.price);
		
		LibraryBook book9 = new LibraryBook();
        book9.title = "The Great Gatsby";
        book9.author = "F. Scott Fitzgerald";
        book9.isbn = "9780743273565";
        book9.publicationYear = 1925;
        book9.genre = "Novel";
        book9.isAvailable = true;
        book9.borrower = "None";
        book9.dueDate = "N/A";
        book9.pages = 218;
        book9.publisher = "Charles Scribner's Sons";
        book9.language = "English";
        book9.isDigital = false;
        book9.format = "Hardcover";
        book9.price = 10.99;
        System.out.println("The Book title is: " + book9.title);
        System.out.println("The Book author is: " + book9.author);
        System.out.println("The Book ISBN is: " + book9.isbn);
        System.out.println("The Book publication year is: " + book9.publicationYear);
        System.out.println("The Book genre is: " + book9.genre);
        System.out.println("The Book is available: " + book9.isAvailable);
        System.out.println("The Book borrower is: " + book9.borrower);
        System.out.println("The Book due date is: " + book9.dueDate);
        System.out.println("The Book pages are: " + book9.pages);
        System.out.println("The Book publisher is: " + book9.publisher);
        System.out.println("The Book language is: " + book9.language);
        System.out.println("The Book is digital: " + book9.isDigital);
        System.out.println("The Book format is: " + book9.format);
        System.out.println("The Book price is: " + book9.price);
		
		LibraryBook book10 = new LibraryBook();
        book10.title = "The Great Gatsby";
        book10.author = "F. Scott Fitzgerald";
        book10.isbn = "9780743273565";
        book10.publicationYear = 1925;
        book10.genre = "Novel";
        book10.isAvailable = true;
        book10.borrower = "None";
        book10.dueDate = "N/A";
        book10.pages = 218;
        book10.publisher = "Charles Scribner's Sons";
        book10.language = "English";
        book10.isDigital = false;
        book10.format = "Hardcover";
        book10.price = 10.99;
        System.out.println("The Book title is: " + book10.title);
        System.out.println("The Book author is: " + book10.author);
        System.out.println("The Book ISBN is: " + book10.isbn);
        System.out.println("The Book publication year is: " + book10.publicationYear);
        System.out.println("The Book genre is: " + book10.genre);
        System.out.println("The Book is available: " + book10.isAvailable);
        System.out.println("The Book borrower is: " + book10.borrower);
        System.out.println("The Book due date is: " + book10.dueDate);
        System.out.println("The Book pages are: " + book10.pages);
        System.out.println("The Book publisher is: " + book10.publisher);
        System.out.println("The Book language is: " + book10.language);
        System.out.println("The Book is digital: " + book10.isDigital);
        System.out.println("The Book format is: " + book10.format);
        System.out.println("The Book price is: " + book10.price);
		
		LibraryBook book11 = new LibraryBook();
        book11.title = "The Great Gatsby";
        book11.author = "F. Scott Fitzgerald";
        book11.isbn = "9780743273565";
        book11.publicationYear = 1925;
        book11.genre = "Novel";
        book11.isAvailable = true;
        book11.borrower = "None";
        book11.dueDate = "N/A";
        book11.pages = 218;
        book11.publisher = "Charles Scribner's Sons";
        book11.language = "English";
        book11.isDigital = false;
        book11.format = "Hardcover";
        book11.price = 10.99;
        System.out.println("The Book title is: " + book11.title);
        System.out.println("The Book author is: " + book11.author);
        System.out.println("The Book ISBN is: " + book11.isbn);
        System.out.println("The Book publication year is: " + book11.publicationYear);
        System.out.println("The Book genre is: " + book11.genre);
        System.out.println("The Book is available: " + book11.isAvailable);
        System.out.println("The Book borrower is: " + book11.borrower);
        System.out.println("The Book due date is: " + book11.dueDate);
        System.out.println("The Book pages are: " + book11.pages);
        System.out.println("The Book publisher is: " + book11.publisher);
        System.out.println("The Book language is: " + book11.language);
        System.out.println("The Book is digital: " + book11.isDigital);
        System.out.println("The Book format is: " + book11.format);
        System.out.println("The Book price is: " + book11.price);
		
		LibraryBook book12 = new LibraryBook();
        book12.title = "The Great Gatsby";
        book12.author = "F. Scott Fitzgerald";
        book12.isbn = "9780743273565";
        book12.publicationYear = 1925;
        book12.genre = "Novel";
        book12.isAvailable = true;
        book12.borrower = "None";
        book12.dueDate = "N/A";
        book12.pages = 218;
        book12.publisher = "Charles Scribner's Sons";
        book12.language = "English";
        book12.isDigital = false;
        book12.format = "Hardcover";
        book12.price = 10.99;
        System.out.println("The Book title is: " + book12.title);
        System.out.println("The Book author is: " + book12.author);
        System.out.println("The Book ISBN is: " + book12.isbn);
        System.out.println("The Book publication year is: " + book12.publicationYear);
        System.out.println("The Book genre is: " + book12.genre);
        System.out.println("The Book is available: " + book12.isAvailable);
        System.out.println("The Book borrower is: " + book12.borrower);
        System.out.println("The Book due date is: " + book12.dueDate);
        System.out.println("The Book pages are: " + book12.pages);
        System.out.println("The Book publisher is: " + book12.publisher);
        System.out.println("The Book language is: " + book12.language);
        System.out.println("The Book is digital: " + book12.isDigital);
        System.out.println("The Book format is: " + book12.format);
        System.out.println("The Book price is: " + book12.price);
		
		LibraryBook book13 = new LibraryBook();
        book13.title = "The Great Gatsby";
        book13.author = "F. Scott Fitzgerald";
        book13.isbn = "9780743273565";
        book13.publicationYear = 1925;
        book13.genre = "Novel";
        book13.isAvailable = true;
        book13.borrower = "None";
        book13.dueDate = "N/A";
        book13.pages = 218;
        book13.publisher = "Charles Scribner's Sons";
        book13.language = "English";
        book13.isDigital = false;
        book13.format = "Hardcover";
        book13.price = 10.99;
        System.out.println("The Book title is: " + book13.title);
        System.out.println("The Book author is: " + book13.author);
        System.out.println("The Book ISBN is: " + book13.isbn);
        System.out.println("The Book publication year is: " + book13.publicationYear);
        System.out.println("The Book genre is: " + book13.genre);
        System.out.println("The Book is available: " + book13.isAvailable);
        System.out.println("The Book borrower is: " + book13.borrower);
        System.out.println("The Book due date is: " + book13.dueDate);
        System.out.println("The Book pages are: " + book13.pages);
        System.out.println("The Book publisher is: " + book13.publisher);
        System.out.println("The Book language is: " + book13.language);
        System.out.println("The Book is digital: " + book13.isDigital);
        System.out.println("The Book format is: " + book13.format);
        System.out.println("The Book price is: " + book13.price);
		
		LibraryBook book14 = new LibraryBook();
        book14.title = "The Great Gatsby";
        book14.author = "F. Scott Fitzgerald";
        book14.isbn = "9780743273565";
        book14.publicationYear = 1925;
        book14.genre = "Novel";
        book14.isAvailable = true;
        book14.borrower = "None";
        book14.dueDate = "N/A";
        book14.pages = 218;
        book14.publisher = "Charles Scribner's Sons";
        book14.language = "English";
        book14.isDigital = false;
        book14.format = "Hardcover";
        book14.price = 10.99;
        System.out.println("The Book title is: " + book14.title);
        System.out.println("The Book author is: " + book14.author);
        System.out.println("The Book ISBN is: " + book14.isbn);
        System.out.println("The Book publication year is: " + book14.publicationYear);
        System.out.println("The Book genre is: " + book14.genre);
        System.out.println("The Book is available: " + book14.isAvailable);
        System.out.println("The Book borrower is: " + book14.borrower);
        System.out.println("The Book due date is: " + book14.dueDate);
        System.out.println("The Book pages are: " + book14.pages);
        System.out.println("The Book publisher is: " + book14.publisher);
        System.out.println("The Book language is: " + book14.language);
        System.out.println("The Book is digital: " + book14.isDigital);
        System.out.println("The Book format is: " + book14.format);
        System.out.println("The Book price is: " + book14.price);
		
		LibraryBook book15 = new LibraryBook();
        book15.title = "The Great Gatsby";
        book15.author = "F. Scott Fitzgerald";
        book15.isbn = "9780743273565";
        book15.publicationYear = 1925;
        book15.genre = "Novel";
        book15.isAvailable = true;
        book15.borrower = "None";
        book15.dueDate = "N/A";
        book15.pages = 218;
        book15.publisher = "Charles Scribner's Sons";
        book15.language = "English";
        book15.isDigital = false;
        book15.format = "Hardcover";
        book15.price = 10.99;
        System.out.println("The Book title is: " + book15.title);
        System.out.println("The Book author is: " + book15.author);
        System.out.println("The Book ISBN is: " + book15.isbn);
        System.out.println("The Book publication year is: " + book15.publicationYear);
        System.out.println("The Book genre is: " + book15.genre);
        System.out.println("The Book is available: " + book15.isAvailable);
        System.out.println("The Book borrower is: " + book15.borrower);
        System.out.println("The Book due date is: " + book15.dueDate);
        System.out.println("The Book pages are: " + book15.pages);
        System.out.println("The Book publisher is: " + book15.publisher);
        System.out.println("The Book language is: " + book15.language);
        System.out.println("The Book is digital: " + book15.isDigital);
        System.out.println("The Book format is: " + book15.format);
        System.out.println("The Book price is: " + book15.price);
		
		LibraryBook book16 = new LibraryBook();
        book16.title = "The Great Gatsby";
        book16.author = "F. Scott Fitzgerald";
        book16.isbn = "9780743273565";
        book16.publicationYear = 1925;
        book16.genre = "Novel";
        book16.isAvailable = true;
        book16.borrower = "None";
        book16.dueDate = "N/A";
        book16.pages = 218;
        book16.publisher = "Charles Scribner's Sons";
        book16.language = "English";
        book16.isDigital = false;
        book16.format = "Hardcover";
        book16.price = 10.99;
        System.out.println("The Book title is: " + book16.title);
        System.out.println("The Book author is: " + book16.author);
        System.out.println("The Book ISBN is: " + book16.isbn);
        System.out.println("The Book publication year is: " + book16.publicationYear);
        System.out.println("The Book genre is: " + book16.genre);
        System.out.println("The Book is available: " + book16.isAvailable);
        System.out.println("The Book borrower is: " + book16.borrower);
        System.out.println("The Book due date is: " + book16.dueDate);
        System.out.println("The Book pages are: " + book16.pages);
        System.out.println("The Book publisher is: " + book16.publisher);
        System.out.println("The Book language is: " + book16.language);
        System.out.println("The Book is digital: " + book16.isDigital);
        System.out.println("The Book format is: " + book16.format);
        System.out.println("The Book price is: " + book16.price);
		
		LibraryBook book17 = new LibraryBook();
        book17.title = "The Great Gatsby";
        book17.author = "F. Scott Fitzgerald";
        book17.isbn = "9780743273565";
        book17.publicationYear = 1925;
        book17.genre = "Novel";
        book17.isAvailable = true;
        book17.borrower = "None";
        book17.dueDate = "N/A";
        book17.pages = 218;
        book17.publisher = "Charles Scribner's Sons";
        book17.language = "English";
        book17.isDigital = false;
        book17.format = "Hardcover";
        book17.price = 10.99;
        System.out.println("The Book title is: " + book17.title);
        System.out.println("The Book author is: " + book17.author);
        System.out.println("The Book ISBN is: " + book17.isbn);
        System.out.println("The Book publication year is: " + book17.publicationYear);
        System.out.println("The Book genre is: " + book17.genre);
        System.out.println("The Book is available: " + book17.isAvailable);
        System.out.println("The Book borrower is: " + book17.borrower);
        System.out.println("The Book due date is: " + book17.dueDate);
        System.out.println("The Book pages are: " + book17.pages);
        System.out.println("The Book publisher is: " + book17.publisher);
        System.out.println("The Book language is: " + book17.language);
        System.out.println("The Book is digital: " + book17.isDigital);
        System.out.println("The Book format is: " + book17.format);
        System.out.println("The Book price is: " + book17.price);
    }
}
