public class MovieRunner 
{
    public static void main(String args[]) 
	{
        new MovieRunner();

        Movie blockbuster = new Movie();
        blockbuster.movieID = "MOV123";
		blockbuster.movieName = "Kalki";
        blockbuster.title = "The Blockbuster";
        blockbuster.genre = "Action";
        blockbuster.director = "John Director";
        blockbuster.language = "Kannada";
        blockbuster.releaseYear = 2024;
        blockbuster.imdbRating = 8.2;
        blockbuster.durationMinutes = 181;
        blockbuster.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster.mainActor = "Prabas";
        blockbuster.mainActress = "AmitaBhachan";
        blockbuster.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster.movieName);
        System.out.println("The blockbuster title is: " + blockbuster.title);
        System.out.println("The blockbuster genre is: " + blockbuster.genre);
        System.out.println("The blockbuster director is: " + blockbuster.director);
        System.out.println("The blockbuster language is: " + blockbuster.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster.isBlockbuster);
		
		Movie blockbuster2 = new Movie();
        blockbuster2.movieID = "MOV123";
		blockbuster2.movieName = "Kalki";
        blockbuster2.title = "The Blockbuster";
        blockbuster2.genre = "Action";
        blockbuster2.director = "John Director";
        blockbuster2.language = "Kannada";
        blockbuster2.releaseYear = 2024;
        blockbuster2.imdbRating = 8.2;
        blockbuster2.durationMinutes = 181;
        blockbuster2.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster2.mainActor = "Prabas";
        blockbuster2.mainActress = "AmitaBhachan";
        blockbuster2.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster2.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster2.movieName);
        System.out.println("The blockbuster title is: " + blockbuster2.title);
        System.out.println("The blockbuster genre is: " + blockbuster2.genre);
        System.out.println("The blockbuster director is: " + blockbuster2.director);
        System.out.println("The blockbuster language is: " + blockbuster2.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster2.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster2.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster2.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster2.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster2.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster2.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster2.isBlockbuster);
		
		Movie blockbuster3 = new Movie();
        blockbuster3.movieID = "MOV123";
		blockbuster3.movieName = "Kalki";
        blockbuster3.title = "The Blockbuster";
        blockbuster3.genre = "Action";
        blockbuster3.director = "John Director";
        blockbuster3.language = "Kannada";
        blockbuster3.releaseYear = 2024;
        blockbuster3.imdbRating = 8.2;
        blockbuster3.durationMinutes = 181;
        blockbuster3.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster3.mainActor = "Prabas";
        blockbuster3.mainActress = "AmitaBhachan";
        blockbuster3.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster3.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster3.movieName);
        System.out.println("The blockbuster title is: " + blockbuster3.title);
        System.out.println("The blockbuster genre is: " + blockbuster3.genre);
        System.out.println("The blockbuster director is: " + blockbuster3.director);
        System.out.println("The blockbuster language is: " + blockbuster3.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster3.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster3.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster3.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster3.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster3.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster3.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster3.isBlockbuster);
		
		Movie blockbuster4 = new Movie();
        blockbuster4.movieID = "MOV123";
		blockbuster4.movieName = "Kalki";
        blockbuster4.title = "The Blockbuster";
        blockbuster4.genre = "Action";
        blockbuster4.director = "John Director";
        blockbuster4.language = "Kannada";
        blockbuster4.releaseYear = 2024;
        blockbuster4.imdbRating = 8.2;
        blockbuster4.durationMinutes = 181;
        blockbuster4.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster4.mainActor = "Prabas";
        blockbuster4.mainActress = "AmitaBhachan";
        blockbuster4.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster4.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster4.movieName);
        System.out.println("The blockbuster title is: " + blockbuster4.title);
        System.out.println("The blockbuster genre is: " + blockbuster4.genre);
        System.out.println("The blockbuster director is: " + blockbuster4.director);
        System.out.println("The blockbuster language is: " + blockbuster4.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster4.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster4.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster4.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster4.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster4.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster4.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster4.isBlockbuster);
		
		Movie blockbuster5 = new Movie();
        blockbuster5.movieID = "MOV123";
		blockbuster5.movieName = "Kalki";
        blockbuster5.title = "The Blockbuster";
        blockbuster5.genre = "Action";
        blockbuster5.director = "John Director";
        blockbuster5.language = "Kannada";
        blockbuster5.releaseYear = 2024;
        blockbuster5.imdbRating = 8.2;
        blockbuster5.durationMinutes = 181;
        blockbuster5.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster5.mainActor = "Prabas";
        blockbuster5.mainActress = "AmitaBhachan";
        blockbuster5.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster5.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster5.movieName);
        System.out.println("The blockbuster title is: " + blockbuster5.title);
        System.out.println("The blockbuster genre is: " + blockbuster5.genre);
        System.out.println("The blockbuster director is: " + blockbuster5.director);
        System.out.println("The blockbuster language is: " + blockbuster5.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster5.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster5.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster5.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster5.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster5.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster5.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster5.isBlockbuster);
		
		Movie blockbuster6 = new Movie();
        blockbuster6.movieID = "MOV123";
		blockbuster6.movieName = "Kalki";
        blockbuster6.title = "The Blockbuster";
        blockbuster6.genre = "Action";
        blockbuster6.director = "John Director";
        blockbuster6.language = "Kannada";
        blockbuster6.releaseYear = 2024;
        blockbuster6.imdbRating = 8.2;
        blockbuster6.durationMinutes = 181;
        blockbuster6.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster6.mainActor = "Prabas";
        blockbuster6.mainActress = "AmitaBhachan";
        blockbuster6.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster6.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster6.movieName);
        System.out.println("The blockbuster title is: " + blockbuster6.title);
        System.out.println("The blockbuster genre is: " + blockbuster6.genre);
        System.out.println("The blockbuster director is: " + blockbuster6.director);
        System.out.println("The blockbuster language is: " + blockbuster6.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster6.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster6.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster6.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster6.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster6.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster6.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster6.isBlockbuster);
		
		Movie blockbuster7 = new Movie();
        blockbuster7.movieID = "MOV123";
		blockbuster7.movieName = "Kalki";
        blockbuster7.title = "The Blockbuster";
        blockbuster7.genre = "Action";
        blockbuster7.director = "John Director";
        blockbuster7.language = "Kannada";
        blockbuster7.releaseYear = 2024;
        blockbuster7.imdbRating = 8.2;
        blockbuster7.durationMinutes = 181;
        blockbuster7.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster7.mainActor = "Prabas";
        blockbuster7.mainActress = "AmitaBhachan";
        blockbuster7.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster7.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster7.movieName);
        System.out.println("The blockbuster title is: " + blockbuster7.title);
        System.out.println("The blockbuster genre is: " + blockbuster7.genre);
        System.out.println("The blockbuster director is: " + blockbuster7.director);
        System.out.println("The blockbuster language is: " + blockbuster7.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster7.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster7.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster7.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster7.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster7.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster7.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster7.isBlockbuster);
		
		Movie blockbuster8 = new Movie();
        blockbuster8.movieID = "MOV123";
		blockbuster8.movieName = "Kalki";
        blockbuster8.title = "The Blockbuster";
        blockbuster8.genre = "Action";
        blockbuster8.director = "John Director";
        blockbuster8.language = "Kannada";
        blockbuster8.releaseYear = 2024;
        blockbuster8.imdbRating = 8.2;
        blockbuster8.durationMinutes = 181;
        blockbuster8.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster8.mainActor = "Prabas";
        blockbuster8.mainActress = "AmitaBhachan";
        blockbuster8.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster8.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster8.movieName);
        System.out.println("The blockbuster title is: " + blockbuster8.title);
        System.out.println("The blockbuster genre is: " + blockbuster8.genre);
        System.out.println("The blockbuster director is: " + blockbuster8.director);
        System.out.println("The blockbuster language is: " + blockbuster8.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster8.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster8.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster8.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster8.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster8.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster8.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster8.isBlockbuster);
		
		Movie blockbuster9 = new Movie();
        blockbuster9.movieID = "MOV123";
		blockbuster9.movieName = "Kalki";
        blockbuster9.title = "The Blockbuster";
        blockbuster9.genre = "Action";
        blockbuster9.director = "John Director";
        blockbuster9.language = "Kannada";
        blockbuster9.releaseYear = 2024;
        blockbuster9.imdbRating = 8.2;
        blockbuster9.durationMinutes = 181;
        blockbuster9.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster9.mainActor = "Prabas";
        blockbuster9.mainActress = "AmitaBhachan";
        blockbuster9.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster9.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster9.movieName);
        System.out.println("The blockbuster title is: " + blockbuster9.title);
        System.out.println("The blockbuster genre is: " + blockbuster9.genre);
        System.out.println("The blockbuster director is: " + blockbuster9.director);
        System.out.println("The blockbuster language is: " + blockbuster9.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster9.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster9.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster9.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster9.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster9.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster9.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster9.isBlockbuster);
		
		Movie blockbuster10 = new Movie();
        blockbuster10.movieID = "MOV123";
		blockbuster10.movieName = "Kalki";
        blockbuster10.title = "The Blockbuster";
        blockbuster10.genre = "Action";
        blockbuster10.director = "John Director";
        blockbuster10.language = "Kannada";
        blockbuster10.releaseYear = 2024;
        blockbuster10.imdbRating = 8.2;
        blockbuster10.durationMinutes = 181;
        blockbuster10.synopsis = "An action-packed movie with thrilling sequences.";
        blockbuster10.mainActor = "Prabas";
        blockbuster10.mainActress = "AmitaBhachan";
        blockbuster10.isBlockbuster = true;
        System.out.println("The blockbuster movieID is: " + blockbuster10.movieID);
		System.out.println("The blockbuster movieName is: " + blockbuster10.movieName);
        System.out.println("The blockbuster title is: " + blockbuster10.title);
        System.out.println("The blockbuster genre is: " + blockbuster10.genre);
        System.out.println("The blockbuster director is: " + blockbuster10.director);
        System.out.println("The blockbuster language is: " + blockbuster10.language);
        System.out.println("The blockbuster releaseYear is: " + blockbuster10.releaseYear);
        System.out.println("The blockbuster imdbRating is: " + blockbuster10.imdbRating);
        System.out.println("The blockbuster durationMinutes is: " + blockbuster10.durationMinutes);
        System.out.println("The blockbuster synopsis is: " + blockbuster10.synopsis);
        System.out.println("The blockbuster mainActor is: " + blockbuster10.mainActor);
        System.out.println("The blockbuster mainActress is: " + blockbuster10.mainActress);
        System.out.println("The blockbuster isBlockbuster is: " + blockbuster10.isBlockbuster);
    }
}
