public class PhoneStoreRunner 
{
    public static void main(String args[]) 
	{
        new PhoneStoreRunner();

        Phone myPhone = new Phone();
        myPhone.imei = "123456789012345";
        myPhone.brand = "Apple";
        myPhone.model = "iPhone 13 Pro";
        myPhone.color = "Graphite";
        myPhone.screenSize = 6.1;
        myPhone.storageGB = 256;
        myPhone.processor = "Apple A15 Bionic";
        myPhone.ramGB = 6;
        myPhone.is5GCapable = true;
        myPhone.price = 1099.0;
        myPhone.osVersion = "iOS 15";
        myPhone.warrantyPeriod = "1 year";
		myPhone.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone.imei);
        System.out.println("Brand: " + myPhone.brand);
        System.out.println("Model: " + myPhone.model);
        System.out.println("Color: " + myPhone.color);
        System.out.println("Screen Size: " + myPhone.screenSize + " inches");
        System.out.println("Storage: " + myPhone.storageGB + " GB");
        System.out.println("Processor: " + myPhone.processor);
        System.out.println("RAM: " + myPhone.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone.is5GCapable);
        System.out.println("Price: $" + myPhone.price);
        System.out.println("OS Version: " + myPhone.osVersion);
        System.out.println("Warranty Period: " + myPhone.warrantyPeriod);
		System.out.println("Weight :" + myPhone.weight);
		
		Phone myPhone2 = new Phone();
        myPhone2.imei = "123456789012345";
        myPhone2.brand = "Apple";
        myPhone2.model = "iPhone 13 Pro";
        myPhone2.color = "Graphite";
        myPhone2.screenSize = 6.1;
        myPhone2.storageGB = 256;
        myPhone2.processor = "Apple A15 Bionic";
        myPhone2.ramGB = 6;
        myPhone2.is5GCapable = true;
        myPhone2.price = 1099.0;
        myPhone2.osVersion = "iOS 15";
        myPhone2.warrantyPeriod = "1 year";
		myPhone2.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone2.imei);
        System.out.println("Brand: " + myPhone2.brand);
        System.out.println("Model: " + myPhone2.model);
        System.out.println("Color: " + myPhone2.color);
        System.out.println("Screen Size: " + myPhone2.screenSize + " inches");
        System.out.println("Storage: " + myPhone2.storageGB + " GB");
        System.out.println("Processor: " + myPhone2.processor);
        System.out.println("RAM: " + myPhone2.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone2.is5GCapable);
        System.out.println("Price: $" + myPhone2.price);
        System.out.println("OS Version: " + myPhone2.osVersion);
        System.out.println("Warranty Period: " + myPhone2.warrantyPeriod);
		System.out.println("Weight :" + myPhone2.weight);
		
		Phone myPhone3 = new Phone();
        myPhone3.imei = "123456789012345";
        myPhone3.brand = "Apple";
        myPhone3.model = "iPhone 13 Pro";
        myPhone3.color = "Graphite";
        myPhone3.screenSize = 6.1;
        myPhone3.storageGB = 256;
        myPhone3.processor = "Apple A15 Bionic";
        myPhone3.ramGB = 6;
        myPhone3.is5GCapable = true;
        myPhone3.price = 1099.0;
        myPhone3.osVersion = "iOS 15";
        myPhone3.warrantyPeriod = "1 year";
		myPhone3.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone3.imei);
        System.out.println("Brand: " + myPhone3.brand);
        System.out.println("Model: " + myPhone3.model);
        System.out.println("Color: " + myPhone3.color);
        System.out.println("Screen Size: " + myPhone3.screenSize + " inches");
        System.out.println("Storage: " + myPhone3.storageGB + " GB");
        System.out.println("Processor: " + myPhone3.processor);
        System.out.println("RAM: " + myPhone3.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone3.is5GCapable);
        System.out.println("Price: $" + myPhone3.price);
        System.out.println("OS Version: " + myPhone3.osVersion);
        System.out.println("Warranty Period: " + myPhone3.warrantyPeriod);
		System.out.println("Weight :" + myPhone3.weight);
		
		Phone myPhone4 = new Phone();
        myPhone4.imei = "123456789012345";
        myPhone4.brand = "Apple";
        myPhone4.model = "iPhone 13 Pro";
        myPhone4.color = "Graphite";
        myPhone4.screenSize = 6.1;
        myPhone4.storageGB = 256;
        myPhone4.processor = "Apple A15 Bionic";
        myPhone4.ramGB = 6;
        myPhone4.is5GCapable = true;
        myPhone4.price = 1099.0;
        myPhone4.osVersion = "iOS 15";
        myPhone4.warrantyPeriod = "1 year";
		myPhone4.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone4.imei);
        System.out.println("Brand: " + myPhone4.brand);
        System.out.println("Model: " + myPhone4.model);
        System.out.println("Color: " + myPhone4.color);
        System.out.println("Screen Size: " + myPhone4.screenSize + " inches");
        System.out.println("Storage: " + myPhone4.storageGB + " GB");
        System.out.println("Processor: " + myPhone4.processor);
        System.out.println("RAM: " + myPhone4.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone4.is5GCapable);
        System.out.println("Price: $" + myPhone4.price);
        System.out.println("OS Version: " + myPhone4.osVersion);
        System.out.println("Warranty Period: " + myPhone4.warrantyPeriod);
		System.out.println("Weight :" + myPhone4.weight);
		
		Phone myPhone5 = new Phone();
        myPhone5.imei = "123456789012345";
        myPhone5.brand = "Apple";
        myPhone5.model = "iPhone 13 Pro";
        myPhone5.color = "Graphite";
        myPhone5.screenSize = 6.1;
        myPhone5.storageGB = 256;
        myPhone5.processor = "Apple A15 Bionic";
        myPhone5.ramGB = 6;
        myPhone5.is5GCapable = true;
        myPhone5.price = 1099.0;
        myPhone5.osVersion = "iOS 15";
        myPhone5.warrantyPeriod = "1 year";
		myPhone5.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone5.imei);
        System.out.println("Brand: " + myPhone5.brand);
        System.out.println("Model: " + myPhone5.model);
        System.out.println("Color: " + myPhone5.color);
        System.out.println("Screen Size: " + myPhone5.screenSize + " inches");
        System.out.println("Storage: " + myPhone5.storageGB + " GB");
        System.out.println("Processor: " + myPhone5.processor);
        System.out.println("RAM: " + myPhone5.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone5.is5GCapable);
        System.out.println("Price: $" + myPhone5.price);
        System.out.println("OS Version: " + myPhone5.osVersion);
        System.out.println("Warranty Period: " + myPhone5.warrantyPeriod);
		System.out.println("Weight :" + myPhone5.weight);
		
		Phone myPhone6 = new Phone();
        myPhone6.imei = "123456789012345";
        myPhone6.brand = "Apple";
        myPhone6.model = "iPhone 13 Pro";
        myPhone6.color = "Graphite";
        myPhone6.screenSize = 6.1;
        myPhone6.storageGB = 256;
        myPhone6.processor = "Apple A15 Bionic";
        myPhone6.ramGB = 6;
        myPhone6.is5GCapable = true;
        myPhone6.price = 1099.0;
        myPhone6.osVersion = "iOS 15";
        myPhone6.warrantyPeriod = "1 year";
		myPhone6.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone6.imei);
        System.out.println("Brand: " + myPhone6.brand);
        System.out.println("Model: " + myPhone6.model);
        System.out.println("Color: " + myPhone6.color);
        System.out.println("Screen Size: " + myPhone6.screenSize + " inches");
        System.out.println("Storage: " + myPhone6.storageGB + " GB");
        System.out.println("Processor: " + myPhone6.processor);
        System.out.println("RAM: " + myPhone6.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone6.is5GCapable);
        System.out.println("Price: $" + myPhone6.price);
        System.out.println("OS Version: " + myPhone6.osVersion);
        System.out.println("Warranty Period: " + myPhone6.warrantyPeriod);
		System.out.println("Weight :" + myPhone6.weight);
		
		Phone myPhone7 = new Phone();
        myPhone7.imei = "123456789012345";
        myPhone7.brand = "Apple";
        myPhone7.model = "iPhone 13 Pro";
        myPhone7.color = "Graphite";
        myPhone7.screenSize = 6.1;
        myPhone7.storageGB = 256;
        myPhone7.processor = "Apple A15 Bionic";
        myPhone7.ramGB = 6;
        myPhone7.is5GCapable = true;
        myPhone7.price = 1099.0;
        myPhone7.osVersion = "iOS 15";
        myPhone7.warrantyPeriod = "1 year";
		myPhone7.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone7.imei);
        System.out.println("Brand: " + myPhone7.brand);
        System.out.println("Model: " + myPhone7.model);
        System.out.println("Color: " + myPhone7.color);
        System.out.println("Screen Size: " + myPhone7.screenSize + " inches");
        System.out.println("Storage: " + myPhone7.storageGB + " GB");
        System.out.println("Processor: " + myPhone7.processor);
        System.out.println("RAM: " + myPhone7.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone7.is5GCapable);
        System.out.println("Price: $" + myPhone7.price);
        System.out.println("OS Version: " + myPhone7.osVersion);
        System.out.println("Warranty Period: " + myPhone7.warrantyPeriod);
		System.out.println("Weight :" + myPhone7.weight);
		
		Phone myPhone8 = new Phone();
        myPhone8.imei = "123456789012345";
        myPhone8.brand = "Apple";
        myPhone8.model = "iPhone 13 Pro";
        myPhone8.color = "Graphite";
        myPhone8.screenSize = 6.1;
        myPhone8.storageGB = 256;
        myPhone8.processor = "Apple A15 Bionic";
        myPhone8.ramGB = 6;
        myPhone8.is5GCapable = true;
        myPhone8.price = 1099.0;
        myPhone8.osVersion = "iOS 15";
        myPhone8.warrantyPeriod = "1 year";
		myPhone8.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone8.imei);
        System.out.println("Brand: " + myPhone8.brand);
        System.out.println("Model: " + myPhone8.model);
        System.out.println("Color: " + myPhone8.color);
        System.out.println("Screen Size: " + myPhone8.screenSize + " inches");
        System.out.println("Storage: " + myPhone8.storageGB + " GB");
        System.out.println("Processor: " + myPhone8.processor);
        System.out.println("RAM: " + myPhone8.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone8.is5GCapable);
        System.out.println("Price: $" + myPhone8.price);
        System.out.println("OS Version: " + myPhone8.osVersion);
        System.out.println("Warranty Period: " + myPhone8.warrantyPeriod);
		System.out.println("Weight :" + myPhone8.weight);
		
		Phone myPhone9 = new Phone();
        myPhone9.imei = "123456789012345";
        myPhone9.brand = "Apple";
        myPhone9.model = "iPhone 13 Pro";
        myPhone9.color = "Graphite";
        myPhone9.screenSize = 6.1;
        myPhone9.storageGB = 256;
        myPhone9.processor = "Apple A15 Bionic";
        myPhone9.ramGB = 6;
        myPhone9.is5GCapable = true;
        myPhone9.price = 1099.0;
        myPhone9.osVersion = "iOS 15";
        myPhone9.warrantyPeriod = "1 year";
		myPhone9.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone9.imei);
        System.out.println("Brand: " + myPhone9.brand);
        System.out.println("Model: " + myPhone9.model);
        System.out.println("Color: " + myPhone9.color);
        System.out.println("Screen Size: " + myPhone9.screenSize + " inches");
        System.out.println("Storage: " + myPhone9.storageGB + " GB");
        System.out.println("Processor: " + myPhone9.processor);
        System.out.println("RAM: " + myPhone9.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone9.is5GCapable);
        System.out.println("Price: $" + myPhone9.price);
        System.out.println("OS Version: " + myPhone9.osVersion);
        System.out.println("Warranty Period: " + myPhone9.warrantyPeriod);
		System.out.println("Weight :" + myPhone9.weight);
		
		Phone myPhone10 = new Phone();
        myPhone10.imei = "123456789012345";
        myPhone10.brand = "Apple";
        myPhone10.model = "iPhone 13 Pro";
        myPhone10.color = "Graphite";
        myPhone10.screenSize = 6.1;
        myPhone10.storageGB = 256;
        myPhone10.processor = "Apple A15 Bionic";
        myPhone10.ramGB = 6;
        myPhone10.is5GCapable = true;
        myPhone10.price = 1099.0;
        myPhone10.osVersion = "iOS 15";
        myPhone10.warrantyPeriod = "1 year";
		myPhone10.weight = 191.3f;
        
        System.out.println("IMEI: " + myPhone10.imei);
        System.out.println("Brand: " + myPhone10.brand);
        System.out.println("Model: " + myPhone10.model);
        System.out.println("Color: " + myPhone10.color);
        System.out.println("Screen Size: " + myPhone10.screenSize + " inches");
        System.out.println("Storage: " + myPhone10.storageGB + " GB");
        System.out.println("Processor: " + myPhone10.processor);
        System.out.println("RAM: " + myPhone10.ramGB + " GB");
        System.out.println("5G Capable: " + myPhone10.is5GCapable);
        System.out.println("Price: $" + myPhone10.price);
        System.out.println("OS Version: " + myPhone10.osVersion);
        System.out.println("Warranty Period: " + myPhone10.warrantyPeriod);
		System.out.println("Weight :" + myPhone10.weight);
    }
}
