public class Product01Runner 
{
	public static void main(String args[]) 
	{
        new Product01Runner();

        Product01 gadget = new Product01();
        gadget.productID = "PRD1234";
        gadget.productName = "Smartphone";
        gadget.category = "Electronics";
        gadget.brand = "TechBrand";
        gadget.price = 799.99;
        gadget.stockQuantity = 1000;
        gadget.supplier = "TechSupplier Ltd.";
        gadget.weight = 0.5;
        gadget.dimensions = "150 x 75 x 8 mm";
        gadget.color = "Black";
        gadget.material = "Aluminum";
        gadget.isReturnable = true;
        gadget.warrantyPeriod = "2 years";
        gadget.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget.productID);
        System.out.println("The gadget productName is: " + gadget.productName);
        System.out.println("The gadget category is: " + gadget.category);
        System.out.println("The gadget brand is: " + gadget.brand);
        System.out.println("The gadget price is: " + gadget.price);
        System.out.println("The gadget stockQuantity is: " + gadget.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget.supplier);
        System.out.println("The gadget weight is: " + gadget.weight);
        System.out.println("The gadget dimensions are: " + gadget.dimensions);
        System.out.println("The gadget color is: " + gadget.color);
        System.out.println("The gadget material is: " + gadget.material);
        System.out.println("The gadget isReturnable is: " + gadget.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget.rating);
		
		Product01 gadget2 = new Product01();
        gadget2.productID = "PRD1234";
        gadget2.productName = "Smartphone";
        gadget2.category = "Electronics";
        gadget2.brand = "TechBrand";
        gadget2.price = 799.99;
        gadget2.stockQuantity = 1000;
        gadget2.supplier = "TechSupplier Ltd.";
        gadget2.weight = 0.5;
        gadget2.dimensions = "150 x 75 x 8 mm";
        gadget2.color = "Black";
        gadget2.material = "Aluminum";
        gadget2.isReturnable = true;
        gadget2.warrantyPeriod = "2 years";
        gadget2.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget2.productID);
        System.out.println("The gadget productName is: " + gadget2.productName);
        System.out.println("The gadget category is: " + gadget2.category);
        System.out.println("The gadget brand is: " + gadget2.brand);
        System.out.println("The gadget price is: " + gadget2.price);
        System.out.println("The gadget stockQuantity is: " + gadget2.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget2.supplier);
        System.out.println("The gadget weight is: " + gadget2.weight);
        System.out.println("The gadget dimensions are: " + gadget2.dimensions);
        System.out.println("The gadget color is: " + gadget2.color);
        System.out.println("The gadget material is: " + gadget2.material);
        System.out.println("The gadget isReturnable is: " + gadget2.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget2.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget2.rating);
		
		Product01 gadget3 = new Product01();
        gadget3.productID = "PRD1234";
        gadget3.productName = "Smartphone";
        gadget3.category = "Electronics";
        gadget3.brand = "TechBrand";
        gadget3.price = 799.99;
        gadget3.stockQuantity = 1000;
        gadget3.supplier = "TechSupplier Ltd.";
        gadget3.weight = 0.5;
        gadget3.dimensions = "150 x 75 x 8 mm";
        gadget3.color = "Black";
        gadget3.material = "Aluminum";
        gadget3.isReturnable = true;
        gadget3.warrantyPeriod = "2 years";
        gadget3.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget3.productID);
        System.out.println("The gadget productName is: " + gadget3.productName);
        System.out.println("The gadget category is: " + gadget3.category);
        System.out.println("The gadget brand is: " + gadget3.brand);
        System.out.println("The gadget price is: " + gadget3.price);
        System.out.println("The gadget stockQuantity is: " + gadget3.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget3.supplier);
        System.out.println("The gadget weight is: " + gadget3.weight);
        System.out.println("The gadget dimensions are: " + gadget3.dimensions);
        System.out.println("The gadget color is: " + gadget3.color);
        System.out.println("The gadget material is: " + gadget3.material);
        System.out.println("The gadget isReturnable is: " + gadget3.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget3.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget3.rating);
		
		Product01 gadget4 = new Product01();
        gadget4.productID = "PRD1234";
        gadget4.productName = "Smartphone";
        gadget4.category = "Electronics";
        gadget4.brand = "TechBrand";
        gadget4.price = 799.99;
        gadget4.stockQuantity = 1000;
        gadget4.supplier = "TechSupplier Ltd.";
        gadget4.weight = 0.5;
        gadget4.dimensions = "150 x 75 x 8 mm";
        gadget4.color = "Black";
        gadget4.material = "Aluminum";
        gadget4.isReturnable = true;
        gadget4.warrantyPeriod = "2 years";
        gadget4.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget4.productID);
        System.out.println("The gadget productName is: " + gadget4.productName);
        System.out.println("The gadget category is: " + gadget4.category);
        System.out.println("The gadget brand is: " + gadget4.brand);
        System.out.println("The gadget price is: " + gadget4.price);
        System.out.println("The gadget stockQuantity is: " + gadget4.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget4.supplier);
        System.out.println("The gadget weight is: " + gadget4.weight);
        System.out.println("The gadget dimensions are: " + gadget4.dimensions);
        System.out.println("The gadget color is: " + gadget4.color);
        System.out.println("The gadget material is: " + gadget4.material);
        System.out.println("The gadget isReturnable is: " + gadget4.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget4.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget4.rating);
		
		Product01 gadget5 = new Product01();
        gadget5.productID = "PRD1234";
        gadget5.productName = "Smartphone";
        gadget5.category = "Electronics";
        gadget5.brand = "TechBrand";
        gadget5.price = 799.99;
        gadget5.stockQuantity = 1000;
        gadget5.supplier = "TechSupplier Ltd.";
        gadget5.weight = 0.5;
        gadget5.dimensions = "150 x 75 x 8 mm";
        gadget5.color = "Black";
        gadget5.material = "Aluminum";
        gadget5.isReturnable = true;
        gadget5.warrantyPeriod = "2 years";
        gadget5.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget5.productID);
        System.out.println("The gadget productName is: " + gadget5.productName);
        System.out.println("The gadget category is: " + gadget5.category);
        System.out.println("The gadget brand is: " + gadget5.brand);
        System.out.println("The gadget price is: " + gadget5.price);
        System.out.println("The gadget stockQuantity is: " + gadget5.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget5.supplier);
        System.out.println("The gadget weight is: " + gadget5.weight);
        System.out.println("The gadget dimensions are: " + gadget5.dimensions);
        System.out.println("The gadget color is: " + gadget5.color);
        System.out.println("The gadget material is: " + gadget5.material);
        System.out.println("The gadget isReturnable is: " + gadget5.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget5.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget5.rating);
		
		Product01 gadget6 = new Product01();
        gadget6.productID = "PRD1234";
        gadget6.productName = "Smartphone";
        gadget6.category = "Electronics";
        gadget6.brand = "TechBrand";
        gadget6.price = 799.99;
        gadget6.stockQuantity = 1000;
        gadget6.supplier = "TechSupplier Ltd.";
        gadget6.weight = 0.5;
        gadget6.dimensions = "150 x 75 x 8 mm";
        gadget6.color = "Black";
        gadget6.material = "Aluminum";
        gadget6.isReturnable = true;
        gadget6.warrantyPeriod = "2 years";
        gadget6.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget6.productID);
        System.out.println("The gadget productName is: " + gadget6.productName);
        System.out.println("The gadget category is: " + gadget6.category);
        System.out.println("The gadget brand is: " + gadget6.brand);
        System.out.println("The gadget price is: " + gadget6.price);
        System.out.println("The gadget stockQuantity is: " + gadget6.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget6.supplier);
        System.out.println("The gadget weight is: " + gadget6.weight);
        System.out.println("The gadget dimensions are: " + gadget6.dimensions);
        System.out.println("The gadget color is: " + gadget6.color);
        System.out.println("The gadget material is: " + gadget6.material);
        System.out.println("The gadget isReturnable is: " + gadget6.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget6.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget6.rating);
		
		Product01 gadget7 = new Product01();
        gadget7.productID = "PRD1234";
        gadget7.productName = "Smartphone";
        gadget7.category = "Electronics";
        gadget7.brand = "TechBrand";
        gadget7.price = 799.99;
        gadget7.stockQuantity = 1000;
        gadget7.supplier = "TechSupplier Ltd.";
        gadget7.weight = 0.5;
        gadget7.dimensions = "150 x 75 x 8 mm";
        gadget7.color = "Black";
        gadget7.material = "Aluminum";
        gadget7.isReturnable = true;
        gadget7.warrantyPeriod = "2 years";
        gadget7.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget7.productID);
        System.out.println("The gadget productName is: " + gadget7.productName);
        System.out.println("The gadget category is: " + gadget7.category);
        System.out.println("The gadget brand is: " + gadget7.brand);
        System.out.println("The gadget price is: " + gadget7.price);
        System.out.println("The gadget stockQuantity is: " + gadget7.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget7.supplier);
        System.out.println("The gadget weight is: " + gadget7.weight);
        System.out.println("The gadget dimensions are: " + gadget7.dimensions);
        System.out.println("The gadget color is: " + gadget7.color);
        System.out.println("The gadget material is: " + gadget7.material);
        System.out.println("The gadget isReturnable is: " + gadget7.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget7.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget7.rating);
		
		Product01 gadget8 = new Product01();
        gadget8.productID = "PRD1234";
        gadget8.productName = "Smartphone";
        gadget8.category = "Electronics";
        gadget8.brand = "TechBrand";
        gadget8.price = 799.99;
        gadget8.stockQuantity = 1000;
        gadget8.supplier = "TechSupplier Ltd.";
        gadget8.weight = 0.5;
        gadget8.dimensions = "150 x 75 x 8 mm";
        gadget8.color = "Black";
        gadget8.material = "Aluminum";
        gadget8.isReturnable = true;
        gadget8.warrantyPeriod = "2 years";
        gadget8.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget8.productID);
        System.out.println("The gadget productName is: " + gadget8.productName);
        System.out.println("The gadget category is: " + gadget8.category);
        System.out.println("The gadget brand is: " + gadget8.brand);
        System.out.println("The gadget price is: " + gadget8.price);
        System.out.println("The gadget stockQuantity is: " + gadget8.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget8.supplier);
        System.out.println("The gadget weight is: " + gadget8.weight);
        System.out.println("The gadget dimensions are: " + gadget8.dimensions);
        System.out.println("The gadget color is: " + gadget8.color);
        System.out.println("The gadget material is: " + gadget8.material);
        System.out.println("The gadget isReturnable is: " + gadget8.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget8.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget8.rating);
		
		Product01 gadget9 = new Product01();
        gadget9.productID = "PRD1234";
        gadget9.productName = "Smartphone";
        gadget9.category = "Electronics";
        gadget9.brand = "TechBrand";
        gadget9.price = 799.99;
        gadget9.stockQuantity = 1000;
        gadget9.supplier = "TechSupplier Ltd.";
        gadget9.weight = 0.5;
        gadget9.dimensions = "150 x 75 x 8 mm";
        gadget9.color = "Black";
        gadget9.material = "Aluminum";
        gadget9.isReturnable = true;
        gadget9.warrantyPeriod = "2 years";
        gadget9.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget9.productID);
        System.out.println("The gadget productName is: " + gadget9.productName);
        System.out.println("The gadget category is: " + gadget9.category);
        System.out.println("The gadget brand is: " + gadget9.brand);
        System.out.println("The gadget price is: " + gadget9.price);
        System.out.println("The gadget stockQuantity is: " + gadget9.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget9.supplier);
        System.out.println("The gadget weight is: " + gadget9.weight);
        System.out.println("The gadget dimensions are: " + gadget9.dimensions);
        System.out.println("The gadget color is: " + gadget9.color);
        System.out.println("The gadget material is: " + gadget9.material);
        System.out.println("The gadget isReturnable is: " + gadget9.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget9.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget9.rating);
		
		Product01 gadget10 = new Product01();
        gadget10.productID = "PRD1234";
        gadget10.productName = "Smartphone";
        gadget10.category = "Electronics";
        gadget10.brand = "TechBrand";
        gadget10.price = 799.99;
        gadget10.stockQuantity = 1000;
        gadget10.supplier = "TechSupplier Ltd.";
        gadget10.weight = 0.5;
        gadget10.dimensions = "150 x 75 x 8 mm";
        gadget10.color = "Black";
        gadget10.material = "Aluminum";
        gadget10.isReturnable = true;
        gadget10.warrantyPeriod = "2 years";
        gadget10.rating = 4.8;
        System.out.println("The gadget productID is: " + gadget10.productID);
        System.out.println("The gadget productName is: " + gadget10.productName);
        System.out.println("The gadget category is: " + gadget10.category);
        System.out.println("The gadget brand is: " + gadget10.brand);
        System.out.println("The gadget price is: " + gadget10.price);
        System.out.println("The gadget stockQuantity is: " + gadget10.stockQuantity);
        System.out.println("The gadget supplier is: " + gadget10.supplier);
        System.out.println("The gadget weight is: " + gadget10.weight);
        System.out.println("The gadget dimensions are: " + gadget10.dimensions);
        System.out.println("The gadget color is: " + gadget10.color);
        System.out.println("The gadget material is: " + gadget10.material);
        System.out.println("The gadget isReturnable is: " + gadget10.isReturnable);
        System.out.println("The gadget warrantyPeriod is: " + gadget10.warrantyPeriod);
        System.out.println("The gadget rating is: " + gadget10.rating);
    }
}