public class Train01Runner 
{
    public static void main(String args[]) 
	{
        new Train01Runner();

        Train01 express1 = new Train01();
        express1.trainNumber = "EXP1234";
        express1.trainName = "Superfast Express";
        express1.departureStation = "San Francisco";
        express1.arrivalStation = "Los Angeles";
        express1.departureTime = "09:00";
        express1.arrivalTime = "15:00";
        express1.durationMinutes = 360;
        express1.ticketClass = "First Class";
        express1.coachType = "Sleeper";
        express1.totalSeats = 200;
        express1.availableSeats = 150;
        express1.isNonStop = true;
        express1.platform = "Platform 1";
        express1.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express1.trainNumber);
        System.out.println("The express trainName is: " + express1.trainName);
        System.out.println("The express departureStation is: " + express1.departureStation);
        System.out.println("The express arrivalStation is: " + express1.arrivalStation);
        System.out.println("The express departureTime is: " + express1.departureTime);
        System.out.println("The express arrivalTime is: " + express1.arrivalTime);
        System.out.println("The express durationMinutes is: " + express1.durationMinutes);
        System.out.println("The express ticketClass is: " + express1.ticketClass);
        System.out.println("The express coachType is: " + express1.coachType);
        System.out.println("The express totalSeats is: " + express1.totalSeats);
        System.out.println("The express availableSeats is: " + express1.availableSeats);
        System.out.println("The express isNonStop is: " + express1.isNonStop);
        System.out.println("The express platform is: " + express1.platform);
        System.out.println("The express terminal is: " + express1.terminal);
		
		Train01 express2 = new Train01();
        express2.trainNumber = "EXP1234";
        express2.trainName = "Superfast Express";
        express2.departureStation = "San Francisco";
        express2.arrivalStation = "Los Angeles";
        express2.departureTime = "09:00";
        express2.arrivalTime = "15:00";
        express2.durationMinutes = 360;
        express2.ticketClass = "First Class";
        express2.coachType = "Sleeper";
        express2.totalSeats = 200;
        express2.availableSeats = 150;
        express2.isNonStop = true;
        express2.platform = "Platform 1";
        express2.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express2.trainNumber);
        System.out.println("The express trainName is: " + express2.trainName);
        System.out.println("The express departureStation is: " + express2.departureStation);
        System.out.println("The express arrivalStation is: " + express2.arrivalStation);
        System.out.println("The express departureTime is: " + express2.departureTime);
        System.out.println("The express arrivalTime is: " + express2.arrivalTime);
        System.out.println("The express durationMinutes is: " + express2.durationMinutes);
        System.out.println("The express ticketClass is: " + express2.ticketClass);
        System.out.println("The express coachType is: " + express2.coachType);
        System.out.println("The express totalSeats is: " + express2.totalSeats);
        System.out.println("The express availableSeats is: " + express2.availableSeats);
        System.out.println("The express isNonStop is: " + express2.isNonStop);
        System.out.println("The express platform is: " + express2.platform);
        System.out.println("The express terminal is: " + express2.terminal);
		
		Train01 express3 = new Train01();
        express3.trainNumber = "EXP1234";
        express3.trainName = "Superfast Express";
        express3.departureStation = "San Francisco";
        express3.arrivalStation = "Los Angeles";
        express3.departureTime = "09:00";
        express3.arrivalTime = "15:00";
        express3.durationMinutes = 360;
        express3.ticketClass = "First Class";
        express3.coachType = "Sleeper";
        express3.totalSeats = 200;
        express3.availableSeats = 150;
        express3.isNonStop = true;
        express3.platform = "Platform 1";
        express3.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express3.trainNumber);
        System.out.println("The express trainName is: " + express3.trainName);
        System.out.println("The express departureStation is: " + express3.departureStation);
        System.out.println("The express arrivalStation is: " + express3.arrivalStation);
        System.out.println("The express departureTime is: " + express3.departureTime);
        System.out.println("The express arrivalTime is: " + express3.arrivalTime);
        System.out.println("The express durationMinutes is: " + express3.durationMinutes);
        System.out.println("The express ticketClass is: " + express3.ticketClass);
        System.out.println("The express coachType is: " + express3.coachType);
        System.out.println("The express totalSeats is: " + express3.totalSeats);
        System.out.println("The express availableSeats is: " + express3.availableSeats);
        System.out.println("The express isNonStop is: " + express3.isNonStop);
        System.out.println("The express platform is: " + express3.platform);
        System.out.println("The express terminal is: " + express3.terminal);
		
		Train01 express4 = new Train01();
        express4.trainNumber = "EXP1234";
        express4.trainName = "Superfast Express";
        express4.departureStation = "San Francisco";
        express4.arrivalStation = "Los Angeles";
        express4.departureTime = "09:00";
        express4.arrivalTime = "15:00";
        express4.durationMinutes = 360;
        express4.ticketClass = "First Class";
        express4.coachType = "Sleeper";
        express4.totalSeats = 200;
        express4.availableSeats = 150;
        express4.isNonStop = true;
        express4.platform = "Platform 1";
        express4.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express4.trainNumber);
        System.out.println("The express trainName is: " + express4.trainName);
        System.out.println("The express departureStation is: " + express4.departureStation);
        System.out.println("The express arrivalStation is: " + express4.arrivalStation);
        System.out.println("The express departureTime is: " + express4.departureTime);
        System.out.println("The express arrivalTime is: " + express4.arrivalTime);
        System.out.println("The express durationMinutes is: " + express4.durationMinutes);
        System.out.println("The express ticketClass is: " + express4.ticketClass);
        System.out.println("The express coachType is: " + express4.coachType);
        System.out.println("The express totalSeats is: " + express4.totalSeats);
        System.out.println("The express availableSeats is: " + express4.availableSeats);
        System.out.println("The express isNonStop is: " + express4.isNonStop);
        System.out.println("The express platform is: " + express4.platform);
        System.out.println("The express terminal is: " + express4.terminal);
		
		Train01 express5 = new Train01();
        express5.trainNumber = "EXP1234";
        express5.trainName = "Superfast Express";
        express5.departureStation = "San Francisco";
        express5.arrivalStation = "Los Angeles";
        express5.departureTime = "09:00";
        express5.arrivalTime = "15:00";
        express5.durationMinutes = 360;
        express5.ticketClass = "First Class";
        express5.coachType = "Sleeper";
        express5.totalSeats = 200;
        express5.availableSeats = 150;
        express5.isNonStop = true;
        express5.platform = "Platform 1";
        express5.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express5.trainNumber);
        System.out.println("The express trainName is: " + express5.trainName);
        System.out.println("The express departureStation is: " + express5.departureStation);
        System.out.println("The express arrivalStation is: " + express5.arrivalStation);
        System.out.println("The express departureTime is: " + express5.departureTime);
        System.out.println("The express arrivalTime is: " + express5.arrivalTime);
        System.out.println("The express durationMinutes is: " + express5.durationMinutes);
        System.out.println("The express ticketClass is: " + express5.ticketClass);
        System.out.println("The express coachType is: " + express5.coachType);
        System.out.println("The express totalSeats is: " + express5.totalSeats);
        System.out.println("The express availableSeats is: " + express5.availableSeats);
        System.out.println("The express isNonStop is: " + express5.isNonStop);
        System.out.println("The express platform is: " + express5.platform);
        System.out.println("The express terminal is: " + express5.terminal);
		
		Train01 express6 = new Train01();
        express6.trainNumber = "EXP1234";
        express6.trainName = "Superfast Express";
        express6.departureStation = "San Francisco";
        express6.arrivalStation = "Los Angeles";
        express6.departureTime = "09:00";
        express6.arrivalTime = "15:00";
        express6.durationMinutes = 360;
        express6.ticketClass = "First Class";
        express6.coachType = "Sleeper";
        express6.totalSeats = 200;
        express6.availableSeats = 150;
        express6.isNonStop = true;
        express6.platform = "Platform 1";
        express6.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express6.trainNumber);
        System.out.println("The express trainName is: " + express6.trainName);
        System.out.println("The express departureStation is: " + express6.departureStation);
        System.out.println("The express arrivalStation is: " + express6.arrivalStation);
        System.out.println("The express departureTime is: " + express6.departureTime);
        System.out.println("The express arrivalTime is: " + express6.arrivalTime);
        System.out.println("The express durationMinutes is: " + express6.durationMinutes);
        System.out.println("The express ticketClass is: " + express6.ticketClass);
        System.out.println("The express coachType is: " + express6.coachType);
        System.out.println("The express totalSeats is: " + express6.totalSeats);
        System.out.println("The express availableSeats is: " + express6.availableSeats);
        System.out.println("The express isNonStop is: " + express6.isNonStop);
        System.out.println("The express platform is: " + express6.platform);
        System.out.println("The express terminal is: " + express6.terminal);
		
		Train01 express7 = new Train01();
        express7.trainNumber = "EXP1234";
        express7.trainName = "Superfast Express";
        express7.departureStation = "San Francisco";
        express7.arrivalStation = "Los Angeles";
        express7.departureTime = "09:00";
        express7.arrivalTime = "15:00";
        express7.durationMinutes = 360;
        express7.ticketClass = "First Class";
        express7.coachType = "Sleeper";
        express7.totalSeats = 200;
        express7.availableSeats = 150;
        express7.isNonStop = true;
        express7.platform = "Platform 1";
        express7.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express7.trainNumber);
        System.out.println("The express trainName is: " + express7.trainName);
        System.out.println("The express departureStation is: " + express7.departureStation);
        System.out.println("The express arrivalStation is: " + express7.arrivalStation);
        System.out.println("The express departureTime is: " + express7.departureTime);
        System.out.println("The express arrivalTime is: " + express7.arrivalTime);
        System.out.println("The express durationMinutes is: " + express7.durationMinutes);
        System.out.println("The express ticketClass is: " + express7.ticketClass);
        System.out.println("The express coachType is: " + express7.coachType);
        System.out.println("The express totalSeats is: " + express7.totalSeats);
        System.out.println("The express availableSeats is: " + express7.availableSeats);
        System.out.println("The express isNonStop is: " + express7.isNonStop);
        System.out.println("The express platform is: " + express7.platform);
        System.out.println("The express terminal is: " + express7.terminal);
		
		Train01 express8 = new Train01();
        express8.trainNumber = "EXP1234";
        express8.trainName = "Superfast Express";
        express8.departureStation = "San Francisco";
        express8.arrivalStation = "Los Angeles";
        express8.departureTime = "09:00";
        express8.arrivalTime = "15:00";
        express8.durationMinutes = 360;
        express8.ticketClass = "First Class";
        express8.coachType = "Sleeper";
        express8.totalSeats = 200;
        express8.availableSeats = 150;
        express8.isNonStop = true;
        express8.platform = "Platform 1";
        express8.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express8.trainNumber);
        System.out.println("The express trainName is: " + express8.trainName);
        System.out.println("The express departureStation is: " + express8.departureStation);
        System.out.println("The express arrivalStation is: " + express8.arrivalStation);
        System.out.println("The express departureTime is: " + express8.departureTime);
        System.out.println("The express arrivalTime is: " + express8.arrivalTime);
        System.out.println("The express durationMinutes is: " + express8.durationMinutes);
        System.out.println("The express ticketClass is: " + express8.ticketClass);
        System.out.println("The express coachType is: " + express8.coachType);
        System.out.println("The express totalSeats is: " + express8.totalSeats);
        System.out.println("The express availableSeats is: " + express8.availableSeats);
        System.out.println("The express isNonStop is: " + express8.isNonStop);
        System.out.println("The express platform is: " + express8.platform);
        System.out.println("The express terminal is: " + express8.terminal);
		
		Train01 express9 = new Train01();
        express9.trainNumber = "EXP1234";
        express9.trainName = "Superfast Express";
        express9.departureStation = "San Francisco";
        express9.arrivalStation = "Los Angeles";
        express9.departureTime = "09:00";
        express9.arrivalTime = "15:00";
        express9.durationMinutes = 360;
        express9.ticketClass = "First Class";
        express9.coachType = "Sleeper";
        express9.totalSeats = 200;
        express9.availableSeats = 150;
        express9.isNonStop = true;
        express9.platform = "Platform 1";
        express9.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express9.trainNumber);
        System.out.println("The express trainName is: " + express9.trainName);
        System.out.println("The express departureStation is: " + express9.departureStation);
        System.out.println("The express arrivalStation is: " + express9.arrivalStation);
        System.out.println("The express departureTime is: " + express9.departureTime);
        System.out.println("The express arrivalTime is: " + express9.arrivalTime);
        System.out.println("The express durationMinutes is: " + express9.durationMinutes);
        System.out.println("The express ticketClass is: " + express9.ticketClass);
        System.out.println("The express coachType is: " + express9.coachType);
        System.out.println("The express totalSeats is: " + express9.totalSeats);
        System.out.println("The express availableSeats is: " + express9.availableSeats);
        System.out.println("The express isNonStop is: " + express9.isNonStop);
        System.out.println("The express platform is: " + express9.platform);
        System.out.println("The express terminal is: " + express9.terminal);
		
		Train01 express10 = new Train01();
        express10.trainNumber = "EXP1234";
        express10.trainName = "Superfast Express";
        express10.departureStation = "San Francisco";
        express10.arrivalStation = "Los Angeles";
        express10.departureTime = "09:00";
        express10.arrivalTime = "15:00";
        express10.durationMinutes = 360;
        express10.ticketClass = "First Class";
        express10.coachType = "Sleeper";
        express10.totalSeats = 200;
        express10.availableSeats = 150;
        express10.isNonStop = true;
        express10.platform = "Platform 1";
        express10.terminal = "Terminal 3";
        System.out.println("The express trainNumber is: " + express10.trainNumber);
        System.out.println("The express trainName is: " + express10.trainName);
        System.out.println("The express departureStation is: " + express10.departureStation);
        System.out.println("The express arrivalStation is: " + express10.arrivalStation);
        System.out.println("The express departureTime is: " + express10.departureTime);
        System.out.println("The express arrivalTime is: " + express10.arrivalTime);
        System.out.println("The express durationMinutes is: " + express10.durationMinutes);
        System.out.println("The express ticketClass is: " + express10.ticketClass);
        System.out.println("The express coachType is: " + express10.coachType);
        System.out.println("The express totalSeats is: " + express10.totalSeats);
        System.out.println("The express availableSeats is: " + express10.availableSeats);
        System.out.println("The express isNonStop is: " + express10.isNonStop);
        System.out.println("The express platform is: " + express10.platform);
        System.out.println("The express terminal is: " + express10.terminal);
    }
}
